from revenue_engine.models.types import ServiceDefinition


def default_service_catalog() -> list[ServiceDefinition]:
    return [
        ServiceDefinition(
            service_key="comai",
            name="COMAI",
            category="ai_platform",
            base_price=45000.0,
            monthly_price=3500.0,
            complexity="high",
            matching_terms=["comai", "ai platform", "intelligence platform", "ai product"],
            target_pains=["ai", "automation", "operations", "decision_making"],
            target_industries=["saas", "software", "fintech", "ecommerce"],
        ),
        ServiceDefinition(
            service_key="custom_ai_development",
            name="Custom AI Development",
            category="ai",
            base_price=35000.0,
            monthly_price=2500.0,
            complexity="high",
            matching_terms=["custom ai", "machine learning", "llm", "openai", "model", "prediction"],
            target_pains=["ai", "automation", "analytics", "decision_making"],
            target_industries=["saas", "software", "healthcare", "fintech"],
        ),
        ServiceDefinition(
            service_key="ai_automation",
            name="AI Automation",
            category="ai",
            base_price=22000.0,
            monthly_price=1800.0,
            complexity="medium",
            matching_terms=["automation", "workflow", "rpa", "process automation", "ai automation"],
            target_pains=["automation", "operations", "manual_process", "efficiency"],
            target_industries=["saas", "ecommerce", "logistics", "manufacturing"],
        ),
        ServiceDefinition(
            service_key="ai_agents",
            name="AI Agents",
            category="ai",
            base_price=28000.0,
            monthly_price=2200.0,
            complexity="high",
            matching_terms=["ai agent", "agents", "autonomous", "copilot", "assistant"],
            target_pains=["support", "operations", "automation", "productivity"],
            target_industries=["saas", "software", "customer_support", "ecommerce"],
        ),
        ServiceDefinition(
            service_key="custom_saas",
            name="Custom SaaS",
            category="software",
            base_price=40000.0,
            monthly_price=3000.0,
            complexity="high",
            matching_terms=["saas", "platform", "multi-tenant", "subscription product", "web app"],
            target_pains=["product", "scaling", "operations", "digital_transformation"],
            target_industries=["saas", "software", "b2b"],
        ),
        ServiceDefinition(
            service_key="mobile_apps",
            name="Mobile Apps",
            category="software",
            base_price=25000.0,
            monthly_price=1200.0,
            complexity="medium",
            matching_terms=["mobile", "ios", "android", "app store", "flutter", "react native"],
            target_pains=["mobile", "customer_experience", "engagement", "product"],
            target_industries=["ecommerce", "consumer", "fintech", "healthcare"],
        ),
        ServiceDefinition(
            service_key="website_development",
            name="Website Development",
            category="web",
            base_price=12000.0,
            monthly_price=600.0,
            complexity="low",
            matching_terms=["website", "landing page", "web development", "corporate site"],
            target_pains=["marketing", "branding", "lead_generation", "customer_experience"],
            target_industries=["services", "ecommerce", "saas", "agency"],
        ),
        ServiceDefinition(
            service_key="shopify_development",
            name="Shopify Development",
            category="ecommerce",
            base_price=15000.0,
            monthly_price=800.0,
            complexity="medium",
            matching_terms=["shopify", "shopify plus", "storefront", "ecommerce store"],
            target_pains=["ecommerce", "checkout", "conversion", "storefront"],
            target_industries=["ecommerce", "retail", "dtc"],
        ),
        ServiceDefinition(
            service_key="woocommerce_development",
            name="WooCommerce Development",
            category="ecommerce",
            base_price=14000.0,
            monthly_price=700.0,
            complexity="medium",
            matching_terms=["woocommerce", "wordpress ecommerce", "wordpress store"],
            target_pains=["ecommerce", "checkout", "conversion", "storefront"],
            target_industries=["ecommerce", "retail", "dtc"],
        ),
        ServiceDefinition(
            service_key="crm_development",
            name="CRM Development",
            category="enterprise",
            base_price=30000.0,
            monthly_price=2000.0,
            complexity="high",
            matching_terms=["crm", "salesforce", "hubspot", "pipeline", "customer relationship"],
            target_pains=["sales", "pipeline", "customer_management", "retention"],
            target_industries=["saas", "b2b", "services", "fintech"],
        ),
        ServiceDefinition(
            service_key="erp_development",
            name="ERP Development",
            category="enterprise",
            base_price=55000.0,
            monthly_price=4000.0,
            complexity="high",
            matching_terms=["erp", "inventory", "finance system", "operations system", "sap"],
            target_pains=["operations", "inventory", "finance", "supply_chain"],
            target_industries=["manufacturing", "retail", "logistics", "wholesale"],
        ),
        ServiceDefinition(
            service_key="api_integration",
            name="API Integration",
            category="integration",
            base_price=18000.0,
            monthly_price=900.0,
            complexity="medium",
            matching_terms=["api", "integration", "webhook", "connector", "middleware"],
            target_pains=["integration", "data_silos", "operations", "automation"],
            target_industries=["saas", "software", "fintech", "ecommerce"],
        ),
        ServiceDefinition(
            service_key="ui_ux",
            name="UI/UX",
            category="design",
            base_price=10000.0,
            monthly_price=500.0,
            complexity="low",
            matching_terms=["ui", "ux", "design system", "prototype", "usability", "interface"],
            target_pains=["customer_experience", "conversion", "product", "usability"],
            target_industries=["saas", "ecommerce", "consumer", "fintech"],
        ),
    ]


def default_service_rules() -> list[dict[str, object]]:
    return [
        {
            "service_key": "custom_ai_development",
            "rule_key": "pain.ai_priority",
            "version": 1,
            "enabled": True,
            "priority": 10,
            "conditions": {"pain_categories": ["ai", "automation", "analytics"]},
            "weight": 1.2,
            "explanation": "Boost Custom AI when AI or automation pains are present.",
        },
        {
            "service_key": "ai_automation",
            "rule_key": "pain.operations_automation",
            "version": 1,
            "enabled": True,
            "priority": 20,
            "conditions": {"pain_categories": ["automation", "operations", "manual_process"]},
            "weight": 1.15,
            "explanation": "Boost AI Automation for operations and workflow pains.",
        },
        {
            "service_key": "shopify_development",
            "rule_key": "industry.ecommerce_shopify",
            "version": 1,
            "enabled": True,
            "priority": 30,
            "conditions": {"industries": ["ecommerce", "retail", "dtc"], "terms": ["shopify"]},
            "weight": 1.25,
            "explanation": "Boost Shopify Development for ecommerce stack signals.",
        },
        {
            "service_key": "crm_development",
            "rule_key": "pain.sales_pipeline",
            "version": 1,
            "enabled": True,
            "priority": 40,
            "conditions": {"pain_categories": ["sales", "pipeline", "retention"]},
            "weight": 1.2,
            "explanation": "Boost CRM Development when sales pipeline pain is evident.",
        },
        {
            "service_key": "api_integration",
            "rule_key": "pain.integration",
            "version": 1,
            "enabled": True,
            "priority": 50,
            "conditions": {"pain_categories": ["integration", "data_silos", "automation"]},
            "weight": 1.1,
            "explanation": "Boost API Integration when systems fragmentation is present.",
        },
    ]
