from __future__ import annotations

from target_account_engine.models.types import ICPProfile


def default_icp_profiles() -> list[ICPProfile]:
    return [
        ICPProfile(
            key="custom_ai_solutions",
            name="Custom AI Solutions",
            service_match="AI Automation",
            priority=10,
            employee_count_min=50,
            employee_count_max=500,
            industries=["software", "saas", "technology", "services", "logistics", "fintech"],
            growth_signals=["growing fast", "expansion", "scaling", "funding"],
            hiring_signals=["operations", "support", "customer success", "automation"],
            technology_stack=["crm", "erp", "zendesk", "intercom", "hubspot", "salesforce"],
            business_models=["b2b", "saas", "services"],
            decision_makers=["cto", "coo", "head of operations", "vp support", "founder"],
            pain_points=[
                "manual workflows",
                "repeated manual work",
                "customer support tools",
                "digital transformation",
            ],
            buying_signals=["funding", "hiring support", "hiring operations", "ai", "automation"],
            negative_signals=["no website", "shutting down", "acquisition complete"],
        ),
        ICPProfile(
            key="inowix",
            name="INOWIX",
            service_match="Inowix",
            priority=15,
            employee_count_min=2,
            employee_count_max=70,
            industries=["saas", "software", "artificial intelligence", "mobile apps"],
            technology_stack=["react", "flutter", "ios", "python", "typescript"],
            business_models=["saas", "b2b", "product"],
            growth_signals=["hiring engineers", "founding engineer", "product launch"],
            hiring_signals=["founding engineer", "full stack", "ios", "flutter", "ai"],
            decision_makers=["ceo", "founder", "cto", "co-founder"],
            pain_points=["capacity overflow", "roadmap ahead of headcount", "need mobile build"],
            buying_signals=["hiring eng", "founders@", "yc jobs"],
            negative_signals=["enterprise 250+", "staffing mill"],
            company_types=["saas_product"],
            headquarters_cities=["Bangalore", "San Francisco", "Mumbai"],
            specialties=["ai", "mobile", "saas"],
        ),
        ICPProfile(
            key="comai",
            name="COMAI",
            service_match="COMAI",
            priority=20,
            employee_count_min=5,
            employee_count_max=100,
            industries=["ecommerce", "retail", "d2c", "consumer", "fashion", "beauty", "jewellery"],
            technology_stack=["shopify", "woocommerce", "magento", "whatsapp", "meta ads"],
            business_models=["d2c", "ecommerce", "marketplace"],
            growth_signals=["repeat orders", "growing support team", "high traffic", "meta ads"],
            hiring_signals=["support", "customer service", "whatsapp", "cx"],
            decision_makers=["head of cx", "founder", "ecommerce manager", "coo", "ceo"],
            pain_points=[
                "high customer support",
                "high whatsapp usage",
                "product catalogue",
                "repeat orders",
                "24-48 hour ticket queues",
            ],
            buying_signals=["support growth", "whatsapp", "catalogue", "d2c growth", "meta ads"],
            negative_signals=["b2b only wholesale", "no online store", "mega brand"],
            company_types=["d2c_brand"],
            headquarters_cities=["Mumbai", "Delhi", "Bangalore", "Surat", "Hyderabad"],
            specialties=["fashion", "beauty", "jewellery", "food", "skincare"],
        ),
        ICPProfile(
            key="website_development",
            name="Website Development",
            service_match="Website Development",
            priority=30,
            industries=["retail", "services", "healthcare", "education", "hospitality", "media"],
            technology_stack=["wordpress", "wix", "squarespace", "drupal"],
            pain_points=[
                "outdated website",
                "low core web vitals",
                "poor lighthouse",
                "weak seo",
                "old ui",
                "no mobile optimization",
                "low conversion",
            ],
            buying_signals=["high traffic", "redesign", "seo", "conversion", "website audit"],
            growth_signals=["high traffic", "expansion", "rebrand"],
            decision_makers=["cmo", "marketing manager", "founder", "growth lead"],
            negative_signals=["brand new website", "agency exclusive retainer"],
        ),
        ICPProfile(
            key="mobile_app_development",
            name="Mobile App Development",
            service_match="Mobile App Development",
            priority=40,
            industries=["software", "fintech", "healthcare", "consumer", "marketplace"],
            hiring_signals=["mobile", "ios", "android", "react native", "flutter"],
            growth_signals=["product launch", "funding", "expansion", "digital transformation"],
            buying_signals=["launching new product", "mobile developers", "funding", "app store"],
            decision_makers=["cto", "product manager", "founder", "vp engineering"],
            pain_points=["no mobile app", "outdated app", "product launch"],
            negative_signals=["native app team fully staffed", "platform freeze"],
        ),
    ]
