"""Verified SaaS / tech product companies for inowix live discovery.

Small/mid-size product companies that may need engineering capacity,
AI integration, or mobile development partners.
"""

from __future__ import annotations

from packages.ecommerce_leads.models import RawEcommerceLead


# Each entry: (company_name, website, industry, city)
SAAS_VERIFIED_BRANDS: list[tuple[str, str, str, str]] = [
    # YC SaaS companies (small teams, likely need capacity)
    ("Nessie Labs", "https://nessielabs.com", "saas", "San Francisco"),
    ("Juno", "https://junocompanion.com", "healthtech", "San Francisco"),
    ("Prematch", "https://prematchapp.de", "saas", "Cologne"),
    ("Hoplite", "https://hoplite.dev", "developer tools", "San Francisco"),
    ("CultOS", "https://cultos.com", "saas", "New York"),
    ("Verve", "https://verve.com", "fintech", "London"),
    ("Zepel", "https://zepel.io", "developer tools", "Bangalore"),
    ("Feather", "https://feather-insurance.com", "fintech", "Berlin"),
    ("Livspace", "https://livspace.com", "marketplace", "Bangalore"),
    ("Mews", "https://mews.com", "saas", "Amsterdam"),
    ("Spendesk", "https://spendesk.com", "fintech", "Paris"),
    ("PriceListo", "https://pricelisto.com", "saas", "Singapore"),
    ("Elenas", "https://elenas.co", "marketplace", "Bogota"),
    ("Dot", "https://dot.me", "saas", "Tel Aviv"),
    ("Elph", "https://elph.com", "fintech", "San Francisco"),
    ("Keel", "https://keel.com", "saas", "London"),
    ("Polywork", "https://polywork.com", "saas", "San Francisco"),
    ("Cron", "https://cron.com", "productivity", "Berlin"),
    ("Ribbon", "https://ribbon.co", "fintech", "New York"),
    ("Pilot", "https://pilot.com", "fintech", "San Francisco"),
    # Indian SaaS companies
    ("Postman", "https://postman.com", "developer tools", "Bangalore"),
    ("Razorpay", "https://razorpay.com", "fintech", "Bangalore"),
    ("Freshworks", "https://freshworks.com", "saas", "Chennai"),
    ("Zoho", "https://zoho.com", "saas", "Chennai"),
    ("InMobi", "https://inmobi.com", "saas", "Bangalore"),
    ("Druva", "https://druva.com", "saas", "Pune"),
    ("CleverTap", "https://clevertap.com", "saas", "Mumbai"),
    ("Whatfix", "https://whatfix.com", "saas", "Bangalore"),
    ("Vakilsearch", "https://vakilsearch.com", "saas", "Chennai"),
    ("NoPaperForms", "https://nopaperforms.com", "saas", "Bangalore"),
    ("Darwinbox", "https://darwinbox.com", "saas", "Hyderabad"),
    ("Hevo Data", "https://hevodata.com", "saas", "Bangalore"),
    ("Kissflow", "https://kissflow.com", "saas", "Chennai"),
    ("Qubole", "https://qubole.com", "saas", "Bangalore"),
    ("RateGain", "https://rategain.com", "saas", "Noida"),
    ("Instamojo", "https://instamojo.com", "saas", "Bangalore"),
    ("Uniphore", "https://uniphore.com", "saas", "Bangalore"),
    ("Yellow.ai", "https://yellow.ai", "saas", "Bangalore"),
    ("Skit.ai", "https://skit.ai", "saas", "Bangalore"),
    # Global SaaS (small teams)
    ("Linear", "https://linear.app", "developer tools", "San Francisco"),
    ("Notion", "https://notion.so", "productivity", "San Francisco"),
    ("Figma", "https://figma.com", "design tools", "San Francisco"),
    ("Vercel", "https://vercel.com", "developer tools", "San Francisco"),
    ("Supabase", "https://supabase.com", "developer tools", "San Francisco"),
    ("Railway", "https://railway.app", "developer tools", "San Francisco"),
    ("Render", "https://render.com", "developer tools", "San Francisco"),
    ("Fly.io", "https://fly.io", "developer tools", "San Francisco"),
    ("Loops", "https://loops.so", "saas", "San Francisco"),
    ("Resend", "https://resend.com", "developer tools", "San Francisco"),
    ("Cal.com", "https://cal.com", "saas", "San Francisco"),
    ("Tldv", "https://tldv.io", "saas", "Berlin"),
    ("Loom", "https://loom.com", "saas", "San Francisco"),
    ("Maze", "https://maze.co", "design tools", "New York"),
    ("Crowd", "https://crowd.dev", "saas", "Berlin"),
    ("Clerk", "https://clerk.com", "developer tools", "San Francisco"),
    ("WorkOS", "https://workos.com", "developer tools", "San Francisco"),
    ("Stytch", "https://stytch.com", "developer tools", "San Francisco"),
    ("Retool", "https://retool.com", "developer tools", "San Francisco"),
    ("Temporal", "https://temporal.io", "developer tools", "San Francisco"),
    # More YC / indie SaaS companies
    ("Inngest", "https://inngest.com", "developer tools", "San Francisco"),
    ("Nango", "https://nango.dev", "developer tools", "San Francisco"),
    ("Mintlify", "https://mintlify.com", "developer tools", "San Francisco"),
    ("Refine", "https://refine.dev", "developer tools", "Berlin"),
    ("Trigger.dev", "https://trigger.dev", "developer tools", "London"),
    ("Bedrock", "https://bedrockdb.com", "developer tools", "San Francisco"),
    ("Hopscotch", "https://hopscotch.xyz", "saas", "San Francisco"),
    ("Formbricks", "https://formbricks.com", "saas", "Berlin"),
    ("Twenty", "https://twenty.com", "saas", "Paris"),
    ("Documenso", "https://documenso.com", "saas", "Berlin"),
    ("Cal.com", "https://cal.com", "saas", "San Francisco"),
    ("Hanko", "https://hanko.io", "developer tools", "Berlin"),
    ("Infisical", "https://infisical.com", "developer tools", "San Francisco"),
    ("Dub", "https://dub.co", "saas", "San Francisco"),
    ("Krunchloop", "https://krunchloop.com", "saas", "Mumbai"),
    ("Fexle", "https://fexle.com", "software services", "Noida"),
    ("ValueLabs", "https://valuelabs.com", "software services", "Hyderabad"),
    ("Mantra Labs", "https://mantralabsglobal.com", "software services", "Bangalore"),
    ("Searce", "https://searce.com", "saas", "Pune"),
    ("Freshcaller", "https://freshcaller.com", "saas", "Chennai"),
    ("BrowserStack", "https://browserstack.com", "saas", "Mumbai"),
    ("Postman", "https://postman.com", "developer tools", "Bangalore"),
    ("Chargebee", "https://chargebee.com", "saas", "Chennai"),
    ("Chargezoom", "https://chargezoom.com", "saas", "New York"),
    # Batch S6-S22 YC companies (small teams, likely need capacity)
    ("Tella", "https://tella.tv", "saas", "San Francisco"),
    ("Sprint", "https://sprint.so", "saas", "San Francisco"),
    ("Tango", "https://tango.us", "saas", "New York"),
    ("RectEq", "https://recteq.app", "saas", "San Francisco"),
    ("Clerky", "https://clerky.com", "saas", "San Francisco"),
    ("Almanac", "https://almanac.io", "saas", "San Francisco"),
    ("Loom", "https://loom.com", "saas", "San Francisco"),
    ("Reline", "https://reline.com", "saas", "San Francisco"),
    ("Rive", "https://rive.app", "design tools", "San Francisco"),
    ("CommandBar", "https://commandbar.com", "saas", "San Francisco"),
    ("Basin", "https://usebasin.com", "developer tools", "San Francisco"),
    ("Knock", "https://knock.app", "saas", "New York"),
    ("Dovetail", "https://dovetail.com", "saas", "Sydney"),
    ("Retool", "https://retool.com", "developer tools", "San Francisco"),
    ("Highlight", "https://highlight.io", "developer tools", "San Francisco"),
    ("Crowd", "https://crowd.dev", "saas", "Berlin"),
    ("Assembly", "https://assembly.com", "saas", "San Francisco"),
    ("Cobalt", "https://cobalt.io", "saas", "San Francisco"),
    ("Swell", "https://swell.is", "saas", "San Francisco"),
    ("Framer", "https://framer.com", "design tools", "Amsterdam"),
    ("Clay", "https://clay.com", "saas", "New York"),
    ("Loops", "https://loops.so", "saas", "San Francisco"),
    ("Dub", "https://dub.co", "saas", "San Francisco"),
    ("Cal.com", "https://cal.com", "saas", "San Francisco"),
    ("Formbricks", "https://formbricks.com", "saas", "Berlin"),
    ("Twenty", "https://twenty.com", "saas", "Paris"),
    ("Documenso", "https://documenso.com", "saas", "Berlin"),
    ("Hanko", "https://hanko.io", "developer tools", "Berlin"),
    ("Infisical", "https://infisical.com", "developer tools", "San Francisco"),
    ("Inngest", "https://inngest.com", "developer tools", "San Francisco"),
    ("Nango", "https://nango.dev", "developer tools", "San Francisco"),
    ("Mintlify", "https://mintlify.com", "developer tools", "San Francisco"),
    ("Trigger.dev", "https://trigger.dev", "developer tools", "London"),
    ("Bedrock", "https://bedrockdb.com", "developer tools", "San Francisco"),
    ("Hopscotch", "https://hopscotch.xyz", "saas", "San Francisco"),
    ("Krunchloop", "https://krunchloop.com", "saas", "Mumbai"),
    ("Fexle", "https://fexle.com", "software services", "Noida"),
    ("ValueLabs", "https://valuelabs.com", "software services", "Hyderabad"),
    ("Mantra Labs", "https://mantralabsglobal.com", "software services", "Bangalore"),
    ("Searce", "https://searce.com", "saas", "Pune"),
    ("BrowserStack", "https://browserstack.com", "saas", "Mumbai"),
    ("Chargebee", "https://chargebee.com", "saas", "Chennai"),
    ("MileIQ", "https://mileiq.com", "saas", "San Francisco"),
    ("Clevertap", "https://clevertap.com", "saas", "Mumbai"),
    ("Appsmith", "https://appsmith.com", "developer tools", "San Francisco"),
    ("Tooljet", "https://tooljet.com", "developer tools", "San Francisco"),
    ("Nocodb", "https://nocodb.com", "developer tools", "San Francisco"),
    ("Metabase", "https://metabase.com", "developer tools", "San Francisco"),
    ("Plane", "https://plane.so", "developer tools", "San Francisco"),
    ("Huly", "https://huly.io", "saas", "San Francisco"),
    ("Chatwoot", "https://chatwoot.com", "saas", "Bangalore"),
    ("Calcom", "https://cal.com", "saas", "San Francisco"),
    ("Middleware", "https://middleware.io", "saas", "Ahmedabad"),
    ("DhiWise", "https://dhiwise.com", "saas", "Ahmedabad"),
    ("Devkit", "https://devkit.xyz", "developer tools", "Bangalore"),
    ("DeployHQ", "https://deployhq.com", "saas", "London"),
    ("Release", "https://releaseapp.io", "saas", "San Francisco"),
    ("Squash", "https://squash.io", "saas", "San Francisco"),
    ("Virtuoso", "https://virtuosoqa.com", "saas", "Bangalore"),
    ("LambdaTest", "https://lambdatest.com", "saas", "Noida"),
    ("TestSigma", "https://testsigma.com", "saas", "Bangalore"),
    ("Keploy", "https://keploy.io", "developer tools", "Bangalore"),
    ("Signoz", "https://signoz.io", "developer tools", "Bangalore"),
    ("Uptrace", "https://uptrace.dev", "developer tools", "San Francisco"),
    ("Grafana", "https://grafana.com", "saas", "San Francisco"),
    ("Qdrant", "https://qdrant.tech", "developer tools", "Berlin"),
    ("Chroma", "https://chromadb.com", "developer tools", "San Francisco"),
    ("Weaviate", "https://weaviate.io", "developer tools", "Amsterdam"),
    ("Pinecone", "https://pinecone.io", "developer tools", "San Francisco"),
    ("Langchain", "https://langchain.com", "developer tools", "San Francisco"),
    ("LlamaIndex", "https://llamaindex.ai", "developer tools", "San Francisco"),
    ("Weights & Biases", "https://wandb.ai", "saas", "San Francisco"),
    ("Scale AI", "https://scale.com", "saas", "San Francisco"),
    ("Snorkel AI", "https://snorkel.ai", "saas", "Redwood City"),
    ("Labelbox", "https://labelbox.com", "saas", "San Francisco"),
    ("Roboflow", "https://roboflow.com", "developer tools", "San Francisco"),
    ("Assembly AI", "https://assemblyai.com", "saas", "San Francisco"),
    ("Deepgram", "https://deepgram.com", "saas", "San Francisco"),
    ("Twelve Labs", "https://twelvelabs.io", "saas", "San Francisco"),
    ("Luma AI", "https://lumalabs.ai", "saas", "San Francisco"),
    ("Runway", "https://runwayml.com", "saas", "New York"),
    ("Stability AI", "https://stability.ai", "saas", "London"),
    ("Replicate", "https://replicate.com", "developer tools", "San Francisco"),
    ("Modal", "https://modal.com", "developer tools", "San Francisco"),
    ("Baseten", "https://baseten.co", "developer tools", "San Francisco"),
    ("Banana", "https://banana.dev", "developer tools", "San Francisco"),
    ("Anyscale", "https://anyscale.com", "developer tools", "San Francisco"),
    ("Together AI", "https://together.ai", "saas", "San Francisco"),
    ("Fireworks AI", "https://fireworks.ai", "saas", "San Francisco"),
    ("Groq", "https://groq.com", "saas", "Mountain View"),
    ("Reka AI", "https://reka.ai", "saas", "San Francisco"),
    ("Cohere", "https://cohere.com", "saas", "Toronto"),
    ("Mistral AI", "https://mistral.ai", "saas", "Paris"),
    ("Aleph Alpha", "https://aleph-alpha.com", "saas", "Heidelberg"),
]


def get_saas_verified_leads() -> list[RawEcommerceLead]:
    """Return SaaS verified brands as RawEcommerceLead objects for live discovery."""
    leads: list[RawEcommerceLead] = []
    for company_name, website, industry, city in SAAS_VERIFIED_BRANDS:
        domain = website.replace("https://", "").replace("http://", "").rstrip("/")
        leads.append(
            RawEcommerceLead(
                company_name=company_name,
                domain=domain,
                industry=industry,
                city=city,
                website=website,
            )
        )
    return leads
