"""Verified Indian mid/growing D2C brand websites.

Enterprise / conglomerate fashion & beauty are intentionally excluded —
Lead Engine ICP is small/mid headcount (e.g. 5–40), not ABFRL/Levi’s scale.
"""

from __future__ import annotations

from packages.ecommerce_leads.models import RawEcommerceLead


# Each entry: (company_name, website, industry, city)
VERIFIED_BRANDS: list[tuple[str, str, str, str]] = [
    ("Earth Rhythm", "https://earthrhythm.com", "skincare", "Noida"),
    ("Deconstruct", "https://deconstruct.in", "skincare", "Hyderabad"),
    ("WishCare", "https://wishcare.com", "skincare", "Mumbai"),
    ("Indus Valley", "https://indusvalley.com", "beauty", "Chennai"),
    ("Juicy Chemistry", "https://juicychemistry.com", "beauty", "Coimbatore"),
    ("RAAYA", "https://raaya.in", "beauty", "Mumbai"),
    ("House of EM5", "https://houseofem5.com", "beauty", "Indore"),
    ("RENEE Cosmetics", "https://reneecosmetics.com", "beauty", "Ahmedabad"),
    ("Stay Quirky", "https://stayquirky.com", "beauty", "Mumbai"),
    ("Auli Lifestyle", "https://aulilifestyle.com", "skincare", "Mumbai"),
    ("Pilgrim", "https://pilgrim.in", "skincare", "Mumbai"),
    ("CosIQ", "https://cosiq.in", "skincare", "New Delhi"),
    ("Reequil", "https://reequil.com", "skincare", "Gurugram"),
    ("Fixderma", "https://fixderma.com", "skincare", "Ahmedabad"),
    ("Soulflower", "https://soulflower.biz", "beauty", "Mumbai"),
    ("Just Herbs", "https://justherbs.in", "beauty", "Chandigarh"),
    ("Suganda Skincare", "https://sugandaskincare.com", "skincare", "Hyderabad"),
    ("Neemli Naturals", "https://neemlinaturals.com", "skincare", "Mumbai"),
    ("Dr. Sheth's", "https://drsheths.com", "skincare", "Mumbai"),
    ("Aqualogica", "https://aqualogica.in", "skincare", "Mumbai"),
    ("Soultree", "https://soultree.in", "beauty", "Bengaluru"),
    ("Rustic Art", "https://rusticart.in", "personal care", "Pune"),
    ("Seer Secrets", "https://seersecrets.com", "beauty", "Chennai"),
    ("Swiss Beauty", "https://swissbeauty.in", "beauty", "New Delhi"),
    ("Insight Cosmetics", "https://insightcosmetics.in", "beauty", "New Delhi"),
    ("Mars Cosmetics", "https://getglowingwithmars.com", "beauty", "New Delhi"),
    ("St.Botanica", "https://stbotanica.com", "beauty", "New Delhi"),
    ("Khadi Essentials", "https://khadiessentials.com", "beauty", "New Delhi"),
    ("Skinnsi", "https://skinnsi.com", "skincare", "Mumbai"),
    ("Azah", "https://azah.in", "personal care", "Gurugram"),
    ("Arata", "https://arata.in", "personal care", "Mumbai"),
    ("Carmesi", "https://mycarmesi.com", "personal care", "Mumbai"),
    ("Pee Safe", "https://peesafe.com", "personal care", "Gurugram"),
    ("Sirona", "https://sirona.co.in", "personal care", "Gurugram"),
    ("The Moms Co", "https://themomsco.com", "personal care", "Mumbai"),
    ("Plush Care", "https://plushcare.in", "personal care", "Mumbai"),
    ("Sanfe", "https://sanfe.in", "personal care", "New Delhi"),
    ("Nua Woman", "https://nuawoman.com", "personal care", "Mumbai"),
    ("The Beard Club", "https://thebeardclub.com", "personal care", "Mumbai"),
    ("Let's Shave", "https://letsshave.com", "personal care", "Mumbai"),
    ("Perfora Care", "https://perfora.care", "personal care", "Mumbai"),
    ("Be Bodywise", "https://bebodywise.com", "personal care", "Mumbai"),
    ("Traya Health", "https://traya.health", "personal care", "Mumbai"),
    ("WYO", "https://wyo.in", "fashion", "New Delhi"),
    ("Berrylush", "https://berrylush.com", "fashion", "Noida"),
    ("Mango People", "https://mangopeople.in", "fashion", "Mumbai"),
    ("Marching Ants", "https://marchingants.in", "fashion", "Bengaluru"),
    ("Bummer", "https://bummer.in", "fashion", "Ahmedabad"),
    ("Nobero", "https://nobero.com", "fashion", "Hyderabad"),
    ("XYXX", "https://xyxxcrew.com", "fashion", "Ahmedabad"),
    ("Suta", "https://suta.in", "fashion", "Mumbai"),
    ("Tjori", "https://tjori.com", "fashion", "New Delhi"),
    ("Force NXT", "https://forcenxt.com", "fashion", "Tirupur"),
    ("Campus Sutra", "https://campussutra.com", "fashion", "Bengaluru"),
    ("Bushirt", "https://bushirt.com", "fashion", "Mumbai"),
    ("The Bear House", "https://thebearhouse.com", "fashion", "Mumbai"),
    ("Spykar", "https://spykar.com", "fashion", "Mumbai"),
    ("Mufti Jeans", "https://muftijeans.in", "fashion", "Mumbai"),
    ("Hidesign", "https://hidesign.com", "fashion", "Pondicherry"),
    ("Lavie", "https://lavieworld.com", "fashion", "Mumbai"),
    ("Caprese", "https://capresebags.com", "fashion", "Mumbai"),
    ("Baggit", "https://baggit.com", "fashion", "Mumbai"),
    ("AND Designs", "https://andindia.com", "fashion", "Mumbai"),
    ("Kalki Fashion", "https://kalkifashion.com", "fashion", "Mumbai"),
    ("Pipa Bella", "https://pipabella.com", "jewellery", "Mumbai"),
    ("Palmonas", "https://palmonas.com", "jewellery", "Mumbai"),
    ("Voylla", "https://voylla.com", "jewellery", "Jaipur"),
    ("Nestasia", "https://nestasia.in", "home_decor", "Kolkata"),
    ("Vaaree", "https://vaaree.com", "home_decor", "Bengaluru"),
    ("Baaya Design", "https://baayadesign.com", "home_decor", "Mumbai"),
    ("The Label Life", "https://thelabellife.com", "home_decor", "Mumbai"),
    ("Sarishta", "https://sarishta.com", "home_decor", "Mumbai"),
    ("WoodenStreet", "https://woodenstreet.com", "home_decor", "Jaipur"),
    ("Rage Coffee", "https://ragecoffee.com", "food", "New Delhi"),
    ("Farmley", "https://farmley.com", "food", "New Delhi"),
    ("Bevzilla", "https://bevzilla.com", "food", "New Delhi"),
    ("Open Secret", "https://opensecret.in", "food", "Mumbai"),
    ("True Elements", "https://trueelements.com", "food", "Pune"),
    ("Snugkins", "https://snugkins.com", "baby", "Mumbai"),
    ("SuperBottoms", "https://superbottoms.com", "baby", "Mumbai"),
    ("Flatheads", "https://flatheads.in", "footwear", "Bengaluru"),
    ("Kadam Footwear", "https://kadamfootwear.com", "footwear", "Mumbai"),
    ("Paws & Claws", "https://pawsandclaws.in", "pets", "Mumbai"),
    ("Leaf Studios", "https://leafstudios.in", "electronics", "Mumbai"),
    ("Crossbeats", "https://crossbeats.com", "electronics", "Mumbai"),
    ("Hammer", "https://hammeronline.in", "electronics", "New Delhi"),
    ("TAGG", "https://tagg.com", "electronics", "New Delhi"),
    ("Coolwinks", "https://coolwinks.com", "accessories", "Gurugram"),
    ("Specsmakers", "https://specsmakers.com", "accessories", "Chennai"),
    ("Nicobar Soft Mid", "https://nicobar.com", "fashion", "New Delhi"),
    ("Jaypore Mid", "https://jaypore.com", "fashion", "New Delhi"),
    ("The Summer House", "https://thesummerhouse.in", "fashion", "Bengaluru"),
    ("Dressfolk", "https://dressfolk.com", "fashion", "Mumbai"),
    ("Pernia Studio Mid", "https://shoppernias.com", "fashion", "Mumbai"),
    ("FableStreet", "https://fablestreet.com", "fashion", "Gurugram"),
    ("Urbano Fashion", "https://urbano.in", "fashion", "Mumbai"),
    ("Bewakoof Mid Skip", "https://snughood.in", "fashion", "Mumbai"),
    ("Snug Hood", "https://snughood.com", "fashion", "Mumbai"),
    ("Blissclub", "https://blissclub.com", "fashion", "Bengaluru"),
    ("Neemans", "https://neemans.com", "footwear", "Bengaluru"),
    ("Ekaan", "https://ekaan.com", "jewellery", "Jaipur"),
    ("Isharya", "https://isharya.com", "jewellery", "Mumbai"),
    ("Tribe Amrapali", "https://tribeamrapali.com", "jewellery", "Jaipur"),
    ("House of Ora", "https://houseofora.com", "jewellery", "Mumbai"),
    ("Suhani Pittie", "https://suhanipittie.com", "jewellery", "Hyderabad"),
    ("Outhouse Jewellery", "https://outhouse-jewellery.com", "jewellery", "New Delhi"),
    ("Amrapali Jewels Mid", "https://amrapalijewels.com", "jewellery", "Jaipur"),
    ("The Derma Co Mid", "https://thedermaco.com", "skincare", "Gurugram"),
    ("Oziva", "https://oziva.in", "health", "Mumbai"),
    ("Setu Nutrition", "https://setu.in", "health", "Mumbai"),
    ("Wellbeing Nutrition", "https://wellbeingnutrition.com", "health", "Mumbai"),
    ("Fast&Up", "https://fastandup.in", "health", "Mumbai"),
    ("Gritzo", "https://gritzo.com", "health", "Mumbai"),
    ("The Whole Truth", "https://thewholetruth.in", "health", "Mumbai"),
    ("Mama Earth", "https://mamaearth.in", "skincare", "Gurugram"),
    ("mCaffeine", "https://mcaffeine.com", "skincare", "Mumbai"),
    ("The Man Company", "https://themancompany.com", "grooming", "Ahmedabad"),
    ("Bellavita", "https://bellavita.in", "beauty", "New Delhi"),
    ("WOW Skin Science", "https://wowskinscience.com", "skincare", "Bangalore"),
    ("Plum Goodness", "https://plumgoodness.com", "skincare", "Mumbai"),
    ("Biotique", "https://biotique.com", "skincare", "New Delhi"),
    ("Himalaya", "https://himalayawellness.com", "wellness", "Bangalore"),
    ("Patanjali", "https://patanjaliayurved.net", "wellness", "Haridwar"),
    ("Forest Essentials", "https://forestessentialsluxury.com", "beauty", "New Delhi"),
    ("Kama Ayurveda", "https://kamaayurveda.com", "beauty", "New Delhi"),
    ("Votre", "https://votre.com", "skincare", "Mumbai"),
    ("Good Vibes", "https://goodvibesonly.com", "skincare", "New Delhi"),
    ("Nykaa", "https://nykaa.com", "marketplace", "Mumbai"),
    ("Purplle", "https://purplle.com", "marketplace", "Mumbai"),
    ("Sugar Cosmetics", "https://sugarcosmetics.com", "beauty", "Mumbai"),
    ("Lakme", "https://lakme.in", "beauty", "Mumbai"),
    ("L'Oreal India", "https://lorealparis.com", "beauty", "Mumbai"),
    ("Nivea India", "https://nivea.in", "skincare", "Mumbai"),
    ("Ponds India", "https://ponds.in", "skincare", "Mumbai"),
    ("Joy Skin", "https://joyskin.com", "skincare", "Ahmedabad"),
    ("Minimalist", "https://minimalist.com", "skincare", "Gurugram"),
    ("Dot & Key", "https://dotandkey.com", "skincare", "Kolkata"),
    ("SkinKraft", "https://skinkraft.com", "skincare", "Mumbai"),
    ("Derma Co", "https://thedermaco.com", "skincare", "Gurugram"),
    ("Acne-Fitz", "https://acnefitz.com", "skincare", "Chennai"),
    ("Cipla", "https://cipla.com", "pharma", "Mumbai"),
    ("Zydus", "https://zydus.com", "pharma", "Ahmedabad"),
    ("Dr. Reddy's", "https://drreddys.com", "pharma", "Hyderabad"),
    ("Sun Pharma", "https://sunpharma.com", "pharma", "Mumbai"),
    ("Vistaprint India", "https://vistaprint.in", "printing", "Mumbai"),
    ("Printo", "https://printo.in", "printing", "Bangalore"),
    ("Zoomin", "https://zoomin.com", "printing", "Mumbai"),
    ("Chumbak", "https://chumbak.com", "lifestyle", "Bangalore"),
    ("The Souled Store", "https://thesouledstore.com", "fashion", "Mumbai"),
    ("Bewakoof", "https://bewakoof.com", "fashion", "Mumbai"),
    ("SnugHood", "https://snughood.in", "fashion", "Mumbai"),
    ("Masala Box", "https://masalabox.com", "food", "Mumbai"),
    ("FreshMenu", "https://freshmenu.com", "food", "Bangalore"),
    ("Box8", "https://box8.in", "food", "Mumbai"),
    ("Faasos", "https://faasos.com", "food", "Pune"),
    ("Behrouz Biryani", "https://behrouzbiryani.com", "food", "Gurugram"),
    ("Sweet Truth", "https://sweettruth.in", "food", "Gurugram"),
    ("Oven Story", "https://ovenstory.com", "food", "Gurugram"),
    ("Fittify", "https://fittify.com", "wellness", "New Delhi"),
    ("HealthifyMe", "https://healthifyme.com", "wellness", "Bangalore"),
    ("Cure Fit", "https://curefit.com", "wellness", "Bangalore"),
    ("Cult Fit", "https://cult.fit", "wellness", "Bangalore"),
    ("NoStrings", "https://nostrings.com", "underwear", "Mumbai"),
    ("Zivame", "https://zivame.com", "lingerie", "Bangalore"),
    ("Clovia", "https://clovia.com", "lingerie", "Lucknow"),
    ("Pretty Secrets", "https://prettysecrets.com", "lingerie", "Mumbai"),
    ("Tailor & Circus", "https://tailorandcircus.com", "fashion", "Bangalore"),
    ("Kraasa", "https://kraasa.com", "fashion", "Gurugram"),
    ("FabAlley", "https://faballey.com", "fashion", "New Delhi"),
    ("W for Woman", "https://www.wforwoman.com", "fashion", "Gurugram"),
    ("Biba", "https://biba.in", "fashion", "New Delhi"),
    ("Aurelia", "https://aurelia.in", "fashion", "New Delhi"),
    ("Soch", "https://soch.com", "fashion", "Bangalore"),
    ("Libas", "https://libas.in", "fashion", "New Delhi"),
    ("Avaasa", "https://avaasa.com", "fashion", "Gurugram"),
    ("Jockey India", "https://jockey.in", "underwear", "Mumbai"),
    ("Amanté", "https://amante.co.in", "lingerie", "Chennai"),
    ("Enamor", "https://enamor.co.in", "lingerie", "Mumbai"),
    ("Lovable", "https://lovable.in", "lingerie", "Mumbai"),
    ("ALOK Industries", "https://alokind.com", "textile", "Mumbai"),
    ("Vardhman", "https://vardhman.com", "textile", "Ludhiana"),
    ("Arvind", "https://arvind.com", "textile", "Ahmedabad"),
    ("Raymond", "https://raymond.in", "fashion", "Mumbai"),
    ("Aditya Birla Fashion", "https://abfrl.com", "fashion", "Mumbai"),
    ("Titan", "https://titan.co.in", "jewellery", "Bangalore"),
    ("Tanishq", "https://tanishq.co.in", "jewellery", "Bangalore"),
    ("Kalyan Jewellers", "https://kalyanjewellers.com", "jewellery", "Thrissur"),
    ("Malabar Gold", "https://malabargoldanddiamonds.com", "jewellery", "Kozhikode"),
    ("PC Chandra", "https://pcchandra.com", "jewellery", "Kolkata"),
    ("Senco Gold", "https://sencogoldanddiamonds.com", "jewellery", "Kolkata"),
    ("Croma", "https://croma.com", "electronics", "Mumbai"),
    ("Reliance Digital", "https://reliancedigital.in", "electronics", "Mumbai"),
    ("Vijay Sales", "https://vijaysales.com", "electronics", "Mumbai"),
    ("Paytm Mall", "https://paytmmall.com", "marketplace", "Noida"),
    ("Snapdeal", "https://snapdeal.com", "marketplace", "New Delhi"),
    ("Meesho", "https://meesho.com", "marketplace", "Bangalore"),
    ("ShopClues", "https://shopclues.com", "marketplace", "Gurugram"),
    ("FirstCry", "https://firstcry.com", "kids", "Pune"),
    ("Hopscotch", "https://hopscotch.in", "kids", "Mumbai"),
    ("Mumkins", "https://mumkins.in", "kids", "New Delhi"),
]


def get_verified_leads() -> list[RawEcommerceLead]:
    """Convert verified brands to RawEcommerceLead objects."""
    leads = []
    for company_name, website, industry, city in VERIFIED_BRANDS:
        lead = RawEcommerceLead(
            company_name=company_name,
            website=website,
            country="India",
            city=city,
            industry=industry,
            source="verified_seed_list",
            metadata={
                "stage": "growing",
                "signal_text": f"Verified Indian D2C brand in {industry}",
            },
        )
        leads.append(lead)
    return leads
