#!/usr/bin/env python3
"""Kochi manufacturers & distributors — chemicals, pharma, fertilizer, agri, biogas.

Discovery approach:
1) Industry directories (chemicalbusinessdirectory, Kompass, IndiaMART, company sites)
2) Official websites + MCA aggregators + LinkedIn public pages for CEO/MD/Director
3) No invented contacts — blanks mean not publicly verified
"""

from __future__ import annotations

import csv
import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "exports"

ROWS = [
    # ——— FERTILIZER / AGRI ———
    {
        "segment": "Fertilizer / Chemicals (PSU)",
        "company_type_role": "Manufacturer",
        "company_name": "The Fertilisers And Chemicals Travancore Ltd (FACT)",
        "location": "Udyogamandal / Ambalamedu, Kochi, Kerala",
        "industry": "Fertilizer & Chemicals",
        "ceo_name": "S. Sakthimani",
        "ceo_title": "Chairman & Managing Director",
        "ceo_email": "cmd@factltd.com",
        "ceo_phone": "04842545418",
        "general_email": "cmd@factltd.com",
        "business_phone": "04842545418",
        "website": "https://fact.co.in",
        "domain": "fact.co.in",
        "other_key_people": "Niranjan S. Sonak / Anupam Misra (Director Marketing — additional charge variants on site)",
        "linkedin_company": "https://www.linkedin.com/company/fertilisers-and-chemicals-travancore-limited",
        "confidence": "high",
        "sources": "fact.co.in board/contact pages + CMD appointment news",
        "notes": "India's first large-scale fertilizer plant; GoI PSU",
    },
    {
        "segment": "Fertilizer / Organic Agri",
        "company_type_role": "Manufacturer + Distributor + Retail",
        "company_name": "South Indian Fertilizers (SIF)",
        "location": "IDA Edayar, Binanipuram, Kochi - 683502",
        "industry": "Organic Fertilizers & Agri Inputs",
        "ceo_name": "R. Sunil Kumar",
        "ceo_title": "Managing Director / Director",
        "ceo_email": "sif@sif.in",
        "ceo_phone": "+917012785820",
        "general_email": "sif@sif.in",
        "business_phone": "+917012785820; +917306394194",
        "website": "https://sif.in",
        "domain": "sif.in",
        "other_key_people": "Group also includes Kochin Agro Nutrients & Chemicals, Geo Agro Tech, Kissan Kendra",
        "linkedin_company": "",
        "confidence": "high",
        "sources": "sif.in about/contact",
        "notes": "Est. 1979; organic fertilizer pioneer in Kerala",
    },
    {
        "segment": "Agriculture / Agrochemicals",
        "company_type_role": "Manufacturer",
        "company_name": "Biota Agro Solutions Pvt. Ltd.",
        "location": "Kuttikkattukara, Kalamassery / Ernakulam, Kochi",
        "industry": "Agrochemicals (Copper fungicides, Bordeaux mix, etc.)",
        "ceo_name": "Thomas Francis",
        "ceo_title": "Director",
        "ceo_email": "",
        "ceo_phone": "+919447236768",
        "general_email": "",
        "business_phone": "04843299785; 04842546776; +919447236768",
        "website": "",
        "domain": "",
        "other_key_people": "",
        "linkedin_company": "",
        "confidence": "medium",
        "sources": "Public director contact listings / company directories",
        "notes": "Copper oxychloride / sulphate / Blue Bordo products",
    },
    # ——— CHEMICALS ———
    {
        "segment": "Chemicals (Heavy / Chlor-alkali)",
        "company_type_role": "Manufacturer (Kerala PSU)",
        "company_name": "The Travancore Cochin Chemicals Ltd (TCC)",
        "location": "Udyogamandal, Kochi - 683501",
        "industry": "Caustic soda, Chlorine & allied chemicals",
        "ceo_name": "Rajeev R (Rajeev Ramakrishnan)",
        "ceo_title": "Managing Director",
        "ceo_email": "tccmd@tcckerala.com",
        "ceo_phone": "",
        "general_email": "tccmd@tcckerala.com",
        "business_phone": "",
        "website": "https://www.tcckerala.com",
        "domain": "tcckerala.com",
        "other_key_people": "Board includes Govt. of Kerala / KSIDC nominees",
        "linkedin_company": "https://www.linkedin.com/company/the-travancore-cochin-chemicals-ltd",
        "confidence": "high",
        "sources": "tcckerala.com board + MCA/Zauba registry email",
        "notes": "Only chlor-alkali unit in Kerala",
    },
    {
        "segment": "Chemicals (Lab / Fine / Agro / Pharma API)",
        "company_type_role": "Manufacturer + Distributor",
        "company_name": "Nice Chemicals Private Limited",
        "location": "Manimala Road, Edappally, Kochi - 682024",
        "industry": "Laboratory fine chemicals, specialty chemicals, agro, glassware",
        "ceo_name": "Venugopal Govindankutty Nair",
        "ceo_title": "Key executive / leadership (public directories); board includes Valsala Ramakrishnan (Wholetime Director)",
        "ceo_email": "mail@nicechemicals.com",
        "ceo_phone": "04842788700",
        "general_email": "mail@nicechemicals.com",
        "business_phone": "04842788700-709",
        "website": "https://nicechemicals.com",
        "domain": "nicechemicals.com",
        "other_key_people": "Valsala Ramakrishnan (Wholetime Director); Sumita Menon (Director — per filings)",
        "linkedin_company": "",
        "confidence": "high",
        "sources": "nicechemicals.com contact + Tracxn/EasyLeadz directors",
        "notes": "Est. 1976; strong lab-chemical brand in South India",
    },
    {
        "segment": "Chemicals (Industrial / Solvents / Detergents)",
        "company_type_role": "Manufacturer + Distributor / Trader",
        "company_name": "Cochin Petromins Pvt Ltd",
        "location": "Binanipuram IDA / Ernakulam, Kochi",
        "industry": "Industrial chemicals, solvents, thinners, detergents",
        "ceo_name": "Unnikrishnan R",
        "ceo_title": "Managing Director",
        "ceo_email": "md@cppl.co.in",
        "ceo_phone": "04842555455",
        "general_email": "md@cppl.co.in",
        "business_phone": "04842555455",
        "website": "https://cppl.co.in",
        "domain": "cppl.co.in",
        "other_key_people": "",
        "linkedin_company": "",
        "confidence": "high",
        "sources": "cppl.co.in + MCA DIN profile (MD)",
        "notes": "Trading since 1993; manufacturing from 2011",
    },
    {
        "segment": "Chemicals (Home / Industrial cleaning)",
        "company_type_role": "Manufacturer + Distributor",
        "company_name": "KSOV Corporation",
        "location": "Edappally, AIMS P.O, Kochi - 682041",
        "industry": "Detergents / laundry & liquid wash chemicals (EKAA World)",
        "ceo_name": "Santhosh Kumar",
        "ceo_title": "Proprietor / Owner",
        "ceo_email": "",
        "ceo_phone": "04842801716",
        "general_email": "",
        "business_phone": "04842801716; 18004253737",
        "website": "https://www.ksovcorporation.com",
        "domain": "ksovcorporation.com",
        "other_key_people": "",
        "linkedin_company": "https://www.linkedin.com/company/ksovcorporation",
        "confidence": "high",
        "sources": "ksovcorporation.com contact + LinkedIn proprietor",
        "notes": "",
    },
    {
        "segment": "Chemicals (Hygiene / Detergents / Pigments)",
        "company_type_role": "Manufacturer + Distributor",
        "company_name": "Jonarin Pigments Private Limited",
        "location": "Kochi, Kerala",
        "industry": "Home hygiene, detergents, industrial laundry chemicals",
        "ceo_name": "Breeze Joseph",
        "ceo_title": "CEO",
        "ceo_email": "chemicals@jonarin.com",
        "ceo_phone": "04842345556",
        "general_email": "chemicals@jonarin.com",
        "business_phone": "04842345556",
        "website": "",
        "domain": "jonarin.com",
        "other_key_people": "Joseph Abraham Arakkathara; Treesa Joseph (Directors — public listings)",
        "linkedin_company": "https://www.linkedin.com/company/jonarin-pigments-private-limited",
        "confidence": "medium",
        "sources": "LinkedIn CEO + public contact directories",
        "notes": "Est. ~1976",
    },
    {
        "segment": "Chemicals (Rubber chemicals / ZnO)",
        "company_type_role": "Manufacturer + Exporter",
        "company_name": "Associated Rubber Chemicals (Kochi) Pvt Ltd",
        "location": "Edappally, Kochi",
        "industry": "Rubber chemicals / zinc oxide",
        "ceo_name": "",
        "ceo_title": "",
        "ceo_email": "marketing@assochem.in",
        "ceo_phone": "04842332134",
        "general_email": "marketing@assochem.in",
        "business_phone": "04842332134; 04842331768; +919349925777",
        "website": "",
        "domain": "assochem.in",
        "other_key_people": "Public contact person listed as Arun TS on trade directories",
        "linkedin_company": "https://www.linkedin.com/company/associated-rubber-chemicals-kochi-pvt-ltd",
        "confidence": "medium",
        "sources": "ANRPC / trade exporter listings",
        "notes": "Also mail@assochem.in / accounts@assochem.in cited publicly",
    },
    {
        "segment": "Chemicals (Activated carbon)",
        "company_type_role": "Manufacturer + Exporter",
        "company_name": "Indo German Carbons Limited (IGCL)",
        "location": "Edayar Industrial Area, Binanipuram, Kochi - 683502",
        "industry": "Coconut-shell activated carbon",
        "ceo_name": "Dr. P. Mohamed Ali",
        "ceo_title": "Chairman (Group / Parent Galfar)",
        "ceo_email": "info@igcl.com",
        "ceo_phone": "04842543092",
        "general_email": "info@igcl.com",
        "business_phone": "04842543092; 04842551986; 04842558106",
        "website": "https://www.igcl.com",
        "domain": "igcl.com",
        "other_key_people": "Promoted with Galfar Engineering & Contracting (Oman)",
        "linkedin_company": "https://www.linkedin.com/company/indo-german-carbons-ltd",
        "confidence": "high",
        "sources": "igcl.com profile page",
        "notes": "Export-oriented activated carbon plant",
    },
    {
        "segment": "Chemicals (Rubber / Specialty)",
        "company_type_role": "Manufacturer",
        "company_name": "Merchem Limited",
        "location": "Grove Centre, Kalamassery, Kochi - 683109",
        "industry": "Rubber chemicals / specialty chemicals",
        "ceo_name": "",
        "ceo_title": "",
        "ceo_email": "",
        "ceo_phone": "04844089300",
        "general_email": "",
        "business_phone": "04844089300",
        "website": "",
        "domain": "",
        "other_key_people": "",
        "linkedin_company": "",
        "confidence": "medium",
        "sources": "Public plant address/phone directories (LookChem etc.)",
        "notes": "MD name/email not clearly verified on open web — follow up via plant switchboard",
    },
    {
        "segment": "Chemicals (Water treatment / specialty)",
        "company_type_role": "Manufacturer",
        "company_name": "Ecodew (Ecodew Pure Water Solutions Pvt Ltd)",
        "location": "Kochi / Aluva area, Kerala",
        "industry": "Water treatment chemicals & solutions",
        "ceo_name": "Muhammed Nujoom",
        "ceo_title": "CEO / Co-Founder / Director",
        "ceo_email": "nujoom@ecodew.solutions",
        "ceo_phone": "+919020661101",
        "general_email": "mail@ecodew.solutions",
        "business_phone": "+919020661101",
        "website": "https://ecodew.solutions",
        "domain": "ecodew.solutions",
        "other_key_people": "Akhil Johny (Co-Founder); Sumayya Rahim (Director)",
        "linkedin_company": "https://www.linkedin.com/company/ecodew",
        "confidence": "high",
        "sources": "Prior Kochi enrichment + LinkedIn/Tofler",
        "notes": "Overlap with earlier Kochi list — included as chemical manufacturer fit",
    },
    # ——— PHARMA ———
    {
        "segment": "Pharma",
        "company_type_role": "Manufacturer / Marketer (formulations)",
        "company_name": "Akesiss Pharma Pvt. Ltd.",
        "location": "Pathadipalam, Edappally, Kochi - 682024",
        "industry": "Pharmaceutical formulations (branded generics)",
        "ceo_name": "Ashok Kumar K (Ashok Kumar Kannampalam)",
        "ceo_title": "Managing Director",
        "ceo_email": "info@akesissindia.com",
        "ceo_phone": "04842544448",
        "general_email": "info@akesissindia.com",
        "business_phone": "04842544448",
        "website": "https://akesiss.com",
        "domain": "akesiss.com",
        "other_key_people": "Padmadas P; Sharath Kumar KK; Thomsan George (Directors – Sales & Marketing)",
        "linkedin_company": "",
        "confidence": "high",
        "sources": "akesiss.com management + TheCompanyCheck",
        "notes": "Founded ~2008/2009",
    },
    {
        "segment": "Pharma",
        "company_type_role": "Pharmaceutical company (marketing / manufacturing partnership model)",
        "company_name": "Rowez Life Sciences Private Limited",
        "location": "Kochi, Kerala",
        "industry": "Pharmaceuticals",
        "ceo_name": "Paily Baby P.X",
        "ceo_title": "Managing Director",
        "ceo_email": "",
        "ceo_phone": "",
        "general_email": "",
        "business_phone": "",
        "website": "https://rowezlifesciences.com",
        "domain": "rowezlifesciences.com",
        "other_key_people": "",
        "linkedin_company": "https://www.linkedin.com/company/rowez-life-sciences-private-limited",
        "confidence": "medium",
        "sources": "LinkedIn MD + company website",
        "notes": "Est. 2008; public email/phone not on homepage crawl — use site contact form / LinkedIn",
    },
    {
        "segment": "Pharma",
        "company_type_role": "Pharmaceutical marketer / company",
        "company_name": "Ezole Pharmaceutical",
        "location": "Kochi, Kerala",
        "industry": "Pharmaceutical formulations marketing",
        "ceo_name": "",
        "ceo_title": "",
        "ceo_email": "",
        "ceo_phone": "",
        "general_email": "",
        "business_phone": "",
        "website": "https://ezolepharmaceutical.com",
        "domain": "ezolepharmaceutical.com",
        "other_key_people": "",
        "linkedin_company": "",
        "confidence": "low",
        "sources": "Company website (presence confirmed); leadership contacts not public",
        "notes": "Claims 100Cr+ business / 300+ staff — good target; needs MCA exact legal name follow-up",
    },
    {
        "segment": "Pharma / Biotech reagents",
        "company_type_role": "Manufacturer / Services",
        "company_name": "GENESPEC Private Limited",
        "location": "CSEZ Kakkanad / Elamakkara, Kochi",
        "industry": "Genomics / sequencing / bioinformatics",
        "ceo_name": "Sajesh Puthenpurackal Krishnankutty",
        "ceo_title": "Director",
        "ceo_email": "info@genespec.com",
        "ceo_phone": "+919744233433",
        "general_email": "info@genespec.com",
        "business_phone": "+919744233433; +917907191205",
        "website": "https://genespec.com",
        "domain": "genespec.com",
        "other_key_people": "Vijayakumar Arun (Director)",
        "linkedin_company": "",
        "confidence": "high",
        "sources": "Prior enrichment + genespec.com/contacts + MCA directors",
        "notes": "Included as life-science / bio manufacturer-service fit",
    },
    {
        "segment": "Pharma / Biotech testing",
        "company_type_role": "Manufacturer / Lab services",
        "company_name": "Merit Biolabs (PVT Merit Biolabs)",
        "location": "Kochi / Ernakulam",
        "industry": "Biotech testing, fermentation, life-science services",
        "ceo_name": "Dr. Achamma Thomas",
        "ceo_title": "CEO / Founder",
        "ceo_email": "meritbiolabs@gmail.com",
        "ceo_phone": "+916238559920",
        "general_email": "meritbiolabs@gmail.com",
        "business_phone": "+916238559920; 04842808384",
        "website": "https://pvtmeritbiolabs.com",
        "domain": "pvtmeritbiolabs.com",
        "other_key_people": "",
        "linkedin_company": "https://www.linkedin.com/company/pvt-merit-biolabs",
        "confidence": "high",
        "sources": "Prior Kochi enrichment",
        "notes": "",
    },
    # ——— BIOGAS ———
    {
        "segment": "Biogas",
        "company_type_role": "Manufacturer + Installer",
        "company_name": "Hind Biogas",
        "location": "Kalamassery Industrial Area, Kochi - 682022",
        "industry": "Biogas plants (domestic / portable / industrial)",
        "ceo_name": "",
        "ceo_title": "",
        "ceo_email": "",
        "ceo_phone": "+917942539636",
        "general_email": "",
        "business_phone": "+917942539636",
        "website": "",
        "domain": "",
        "other_key_people": "",
        "linkedin_company": "https://www.linkedin.com/company/hind-biogas",
        "confidence": "medium",
        "sources": "IndiaMART Ernakulam listings + LinkedIn company",
        "notes": "Also listed phones 73211190 / 84191920 on LinkedIn snippet — verify before outreach",
    },
    {
        "segment": "Biogas",
        "company_type_role": "Manufacturer + Installer",
        "company_name": "Navajyothi Biogas",
        "location": "Eloor, Kochi / Ernakulam - 683501",
        "industry": "Biogas plants (villa / apartment / commercial)",
        "ceo_name": "",
        "ceo_title": "Proprietorship (est. 2016)",
        "ceo_email": "",
        "ceo_phone": "",
        "general_email": "",
        "business_phone": "",
        "website": "",
        "domain": "",
        "other_key_people": "",
        "linkedin_company": "",
        "confidence": "low",
        "sources": "IndiaMART + TheCompanyCheck org profile (Eloor)",
        "notes": "Strong product fit; proprietor name/email behind IndiaMART login — enrich via call/GST",
    },
    {
        "segment": "Chemicals / Peptides",
        "company_type_role": "Manufacturer",
        "company_name": "Biosix Peptides (India) Pvt. Ltd.",
        "location": "KINFRA Hi-Tech Park, Kalamassery, Kochi",
        "industry": "Peptides / chemical manufacturing",
        "ceo_name": "Mullassery Gopalakrishnan Joshy",
        "ceo_title": "Managing Director",
        "ceo_email": "kkrcca66@gmail.com",
        "ceo_phone": "",
        "general_email": "kkrcca66@gmail.com",
        "business_phone": "",
        "website": "",
        "domain": "",
        "other_key_people": "Manakulangaraparambil Asharaff Sultan (Director)",
        "linkedin_company": "",
        "confidence": "medium",
        "sources": "Prior Kochi enrichment / MCA aggregators",
        "notes": "",
    },
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    n = len(ROWS)
    summary = {
        "total": n,
        "by_segment": {},
        "with_ceo_name": sum(1 for r in ROWS if r["ceo_name"]),
        "with_email": sum(1 for r in ROWS if r["ceo_email"] or r["general_email"]),
        "with_phone": sum(1 for r in ROWS if r["ceo_phone"] or r["business_phone"]),
        "with_website": sum(1 for r in ROWS if r["website"] or r["domain"]),
        "high_confidence": sum(1 for r in ROWS if r["confidence"] == "high"),
        "medium_confidence": sum(1 for r in ROWS if r["confidence"] == "medium"),
        "low_confidence": sum(1 for r in ROWS if r["confidence"] == "low"),
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "geography": "Kochi / Ernakulam industrial belt (Udyogamandal, Edayar, Edappally, Kalamassery, Eloor)",
        "method": "Directory discovery → official sites → MCA/LinkedIn public → QA (no invented contacts)",
    }
    for r in ROWS:
        seg = r["segment"].split("(")[0].strip()
        # coarse buckets
        if "Fertilizer" in r["segment"] or "Agri" in r["segment"] or "Agriculture" in r["segment"]:
            bucket = "Fertilizer/Agri"
        elif "Pharma" in r["segment"] or "Biotech" in r["segment"]:
            bucket = "Pharma/Biotech"
        elif "Biogas" in r["segment"]:
            bucket = "Biogas"
        else:
            bucket = "Chemicals"
        summary["by_segment"][bucket] = summary["by_segment"].get(bucket, 0) + 1

    json_path = OUT / "kochi_mfr_distributor_leads_final.json"
    csv_path = OUT / "kochi_mfr_distributor_leads_final.csv"
    md_path = OUT / "kochi_mfr_distributor_leads_final.md"

    json_path.write_text(
        json.dumps({"summary": summary, "leads": ROWS}, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    fields = list(ROWS[0].keys())
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        w.writerows(ROWS)

    lines = [
        "# Kochi Manufacturers & Distributors — Chemicals / Pharma / Fertilizer / Agri / Biogas",
        "",
        f"- Total leads: **{summary['total']}**",
        f"- With CEO/MD/Director name: **{summary['with_ceo_name']}**",
        f"- With email: **{summary['with_email']}**",
        f"- With phone: **{summary['with_phone']}**",
        f"- Segments: {summary['by_segment']}",
        "",
        "| Segment | Company | Role | Leader | Email | Phone | Conf. |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in ROWS:
        lines.append(
            f"| {r['segment']} | {r['company_name']} | {r['company_type_role']} | "
            f"{r['ceo_name'] or '—'} | {r['ceo_email'] or r['general_email'] or '—'} | "
            f"{r['ceo_phone'] or r['business_phone'] or '—'} | {r['confidence']} |"
        )
    lines += [
        "",
        "## Discovery method",
        "1. Industry directories (chemicalbusinessdirectory, Kompass, IndiaMART, trade listings)",
        "2. Official company websites for HQ confirmation + contact pages",
        "3. MCA aggregators + LinkedIn public pages for CEO/MD/Director",
        "4. QA: only Kochi/Ernakulam-based manufacturers & distributors; no invented emails",
        "",
        "## Priority outreach (high confidence + email)",
        "- FACT — cmd@factltd.com",
        "- TCC — tccmd@tcckerala.com",
        "- Nice Chemicals — mail@nicechemicals.com",
        "- Cochin Petromins — md@cppl.co.in",
        "- SIF — sif@sif.in",
        "- Akesiss Pharma — info@akesissindia.com",
        "- IGCL — info@igcl.com",
        "- Ecodew — nujoom@ecodew.solutions",
    ]
    md_path.write_text("\n".join(lines), encoding="utf-8")
    (OUT / "kochi_mfr_distributor_leads_final_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))
    print("Wrote", csv_path)


if __name__ == "__main__":
    main()
