"""Insert extra agency leads into PostgreSQL."""
import json
import uuid
import asyncpg
import asyncio

EXTRA_LEADS = [
    {"agency_name": "Marketing Lab", "country": "India", "agency_type": "Performance Marketing Agency", "clients": "22+ Shark Tank India brands", "client_count": 22, "decision_maker": "Mintu", "decision_maker_role": "Founder", "contactability": "MEDIUM", "services": ["Performance Marketing", "Full-Funnel D2C Marketing"], "tier": "C", "client_access_score": 60, "comai_fit_score": 70, "final_score": 65, "why_this_agency": "22+ Shark Tank India brands. 800% surge in daily sales.", "comai_fit": "Shark Tank brands need WhatsApp commerce.", "pitch_angle": "Marketing Lab scales Shark Tank brands. COMAI adds WhatsApp commerce.", "source": "manual_research"},
    {"agency_name": "Drop Scale Media", "country": "India", "agency_type": "Performance Marketing Agency", "clients": "52+ D2C brands", "client_count": 52, "revenue_managed": "3.3Cr ad spend managed", "contactability": "LOW", "services": ["Meta Ads", "Performance Marketing", "D2C Scaling"], "tier": "C", "client_access_score": 60, "comai_fit_score": 65, "final_score": 63, "why_this_agency": "52+ D2C brands. 5.7+ avg ROAS.", "comai_fit": "D2C brands need WhatsApp commerce.", "pitch_angle": "Drop Scale Media manages 52+ D2C brands. COMAI adds WhatsApp commerce.", "source": "manual_research"},
    {"agency_name": "ROI Hunt", "country": "India", "agency_type": "Performance Marketing Agency", "clients": "E-commerce and D2C brands", "revenue_managed": "18.4Cr+ ad spend, 148Cr revenue", "contactability": "MEDIUM", "services": ["Google Ads", "Meta Ads", "E-commerce Marketing", "Email Marketing"], "tier": "C", "client_access_score": 65, "comai_fit_score": 65, "final_score": 65, "why_this_agency": "6.12x ROAS over 12 months. 148Cr revenue generated.", "comai_fit": "E-commerce brands need WhatsApp commerce.", "pitch_angle": "ROI Hunt generates 148Cr revenue. COMAI adds WhatsApp commerce layer.", "source": "manual_research"},
    {"agency_name": "Akestech", "country": "India", "agency_type": "Performance Marketing Agency", "clients": "200+ Shopify stores", "client_count": 200, "revenue_managed": "50Cr+ ad spend managed", "contactability": "MEDIUM", "services": ["Meta Ads", "Google Ads", "Creative Strategy", "CRO", "Attribution"], "tier": "C", "client_access_score": 65, "comai_fit_score": 70, "final_score": 67, "why_this_agency": "200+ Shopify stores. 50Cr+ ad spend. 15+ creatives/month.", "comai_fit": "Shopify stores are perfect for COMAI integration.", "pitch_angle": "Akestech manages 200+ Shopify stores. COMAI installs in 15 minutes.", "source": "manual_research"},
    {"agency_name": "ShivOhm Infotech", "country": "India", "city": "Ahmedabad", "agency_type": "Performance Marketing Agency", "clients": "Shopify-first beauty, skincare, fashion brands", "decision_maker": "Manav", "decision_maker_role": "Founder", "email": "manav@shivohminfotech.com", "phone": "+91-9408377432", "contactability": "HIGH", "services": ["Meta Ads", "Google Ads", "Shopify CRO", "WhatsApp", "Email"], "tier": "C", "client_access_score": 60, "comai_fit_score": 75, "final_score": 67, "why_this_agency": "Shopify-first beauty/skincare/fashion. 3-month growth commitment model.", "comai_fit": "Already does WhatsApp retention. COMAI automates it.", "pitch_angle": "ShivOhm does WhatsApp retention manually. COMAI automates with AI chatbot.", "source": "manual_research"},
    {"agency_name": "Studio 8X", "country": "India", "agency_type": "Full-Stack D2C Growth Agency", "decision_maker": "Ajay", "decision_maker_role": "Founder", "contactability": "MEDIUM", "services": ["Strategy", "Marketing", "Growth Hacking", "Product", "Technology", "Operations"], "tier": "C", "client_access_score": 60, "comai_fit_score": 65, "final_score": 63, "why_this_agency": "Revenue-linked model. Ex-Akasa Air, Apollo 24/7, Hero Cycles. 18+ years.", "comai_fit": "Full-stack D2C needs WhatsApp commerce.", "pitch_angle": "Studio 8X does full-stack D2C. COMAI adds WhatsApp commerce.", "source": "manual_research"},
    {"agency_name": "Pravis", "country": "India", "agency_type": "Creative and Influencer Agency", "clients": "Consumer brands at growth stage", "contactability": "MEDIUM", "services": ["Creative", "Social Media", "Influencer Marketing", "Performance Marketing"], "tier": "C", "client_access_score": 60, "comai_fit_score": 60, "final_score": 60, "why_this_agency": "Built Momspresso (25M users, sold to Mamaearth). 11500+ influencers.", "comai_fit": "Consumer brands need WhatsApp commerce.", "pitch_angle": "Pravis built and sold Momspresso. COMAI adds WhatsApp commerce to their portfolio.", "source": "manual_research"},
    {"agency_name": "RankMyShopify", "country": "India", "city": "Punjab", "agency_type": "Shopify Marketing Agency", "clients": "500+ ecommerce brands", "client_count": 500, "contactability": "MEDIUM", "services": ["SEO", "Google Ads", "Meta Ads", "CRO", "Email Marketing", "Analytics"], "certifications": ["Shopify Plus Partner"], "tier": "C", "client_access_score": 70, "comai_fit_score": 70, "final_score": 70, "why_this_agency": "500+ ecommerce brands. 15+ years Shopify-only focus. Shopify Plus Partner.", "comai_fit": "Every Shopify store is a potential COMAI installation.", "pitch_angle": "RankMyShopify serves 500+ Shopify stores. COMAI installs on all of them.", "source": "manual_research"},
    {"agency_name": "Frameleads", "country": "India", "city": "Mumbai", "agency_type": "D2C Performance Agency", "clients": "D2C brands across categories", "contactability": "MEDIUM", "services": ["Meta Ads", "Google Ads", "WhatsApp Marketing", "Email Automation", "SEO", "CRO"], "tier": "C", "client_access_score": 60, "comai_fit_score": 75, "final_score": 67, "why_this_agency": "20-50 creative variants/month. WhatsApp marketing included. ASC+, CBO.", "comai_fit": "Already does WhatsApp marketing. COMAI automates and scales.", "pitch_angle": "Frameleads does WhatsApp marketing. COMAI automates with AI chatbot + cart recovery.", "source": "manual_research"},
    {"agency_name": "Social Dharma", "country": "India", "agency_type": "Performance Marketing Agency", "clients": "D2C brands", "contactability": "MEDIUM", "services": ["Meta Ads", "Google Ads", "Retention Marketing", "WhatsApp Flows", "ROAS Optimization"], "tier": "C", "client_access_score": 60, "comai_fit_score": 75, "final_score": 67, "why_this_agency": "Retention marketing focus. WhatsApp flows. Free 30-min audit.", "comai_fit": "Already does WhatsApp flows. COMAI scales with AI.", "pitch_angle": "Social Dharma does WhatsApp flows. COMAI automates with AI chatbot + commerce.", "source": "manual_research"},
    {"agency_name": "Green Giraffes", "country": "India", "agency_type": "Brand Strategy and Growth Agency", "clients": "Wakefit, Fable Street, Sirona", "contactability": "MEDIUM", "services": ["Brand Strategy", "Marketplace Growth", "D2C Growth", "Brand Campaigns"], "tier": "C", "client_access_score": 60, "comai_fit_score": 65, "final_score": 63, "why_this_agency": "NIFT and ISB alumni. 22+ years fashion/lifestyle. Scaled Sirona.", "comai_fit": "D2C brands need WhatsApp commerce.", "pitch_angle": "Green Giraffes scales brands like Sirona. COMAI adds WhatsApp commerce.", "source": "manual_research"},
    {"agency_name": "Tenet", "country": "India", "city": "Noida/Gurgaon", "agency_type": "D2C Branding Agency", "clients": "200+ D2C brands", "client_count": 200, "contactability": "MEDIUM", "services": ["Brand Strategy", "Identity", "Packaging", "Digital Presence"], "tier": "C", "client_access_score": 65, "comai_fit_score": 60, "final_score": 63, "why_this_agency": "200+ D2C brands. 95%+ client return rate. 7+ Fortune 1000-backed D2C brands.", "comai_fit": "D2C brands need WhatsApp commerce.", "pitch_angle": "Tenet serves 200+ D2C brands. COMAI adds WhatsApp commerce layer.", "source": "manual_research"},
    {"agency_name": "Suramya", "country": "India", "city": "Noida", "agency_type": "Brand Design Agency", "clients": "200+ projects (India, UAE, USA)", "client_count": 200, "contactability": "MEDIUM", "services": ["Brand Strategy", "Identity", "Packaging", "UI/UX", "Marketing Strategy"], "tier": "C", "client_access_score": 60, "comai_fit_score": 60, "final_score": 60, "why_this_agency": "200+ projects. 4.9 client rating. 90% repeat business.", "comai_fit": "Brand design clients need WhatsApp commerce.", "pitch_angle": "Suramya designs brands. COMAI adds WhatsApp commerce to their clients.", "source": "manual_research"},
    {"agency_name": "Precision Digitech", "country": "India", "agency_type": "Performance Marketing Agency", "clients": "D2C brands", "contactability": "MEDIUM", "services": ["Meta Ads", "Google Ads", "Performance Creatives", "D2C Scaling", "CRO"], "tier": "C", "client_access_score": 60, "comai_fit_score": 65, "final_score": 63, "why_this_agency": "Scaled brand from 20L to 1.1Cr/month in 12 months.", "comai_fit": "D2C brands need WhatsApp commerce.", "pitch_angle": "Precision Digitech scales D2C brands. COMAI adds WhatsApp commerce.", "source": "manual_research"},
    {"agency_name": "Viral Groww", "country": "India", "agency_type": "Performance Marketing Agency", "clients": "D2C and ecommerce brands", "revenue_managed": "3Cr+ ad spend, 10Cr+ revenue", "contactability": "MEDIUM", "services": ["Meta Ads", "Full-Funnel Campaigns", "Ecommerce Growth"], "tier": "C", "client_access_score": 60, "comai_fit_score": 65, "final_score": 63, "why_this_agency": "3Cr+ ad spend. 10Cr+ revenue. 5+ ROAS.", "comai_fit": "Ecommerce brands need WhatsApp commerce.", "pitch_angle": "Viral Groww generates 10Cr+ revenue. COMAI adds WhatsApp commerce.", "source": "manual_research"},
    {"agency_name": "G4 Growth", "country": "India", "agency_type": "D2C Growth Agency", "clients": "D2C brands", "contactability": "MEDIUM", "services": ["Meta Ads", "Google Ads", "CRO", "Creative", "Automation", "CRM"], "tier": "C", "client_access_score": 60, "comai_fit_score": 70, "final_score": 65, "why_this_agency": "Full-funnel, LTV-focused approach. Automation and CRM.", "comai_fit": "LTV-focused means they need WhatsApp commerce.", "pitch_angle": "G4 Growth focuses on LTV. COMAI drives repeat purchases via WhatsApp.", "source": "manual_research"},
    {"agency_name": "Spell Growth", "country": "India", "agency_type": "Growth Marketing Agency", "clients": "D2C brands, coaches, creators, startups", "contactability": "MEDIUM", "services": ["Growth Marketing", "Conversion Websites", "R&D-Based Marketing"], "tier": "C", "client_access_score": 55, "comai_fit_score": 65, "final_score": 60, "why_this_agency": "Flexible pricing (revenue sharing/equity for startups). R&D approach.", "comai_fit": "D2C brands need WhatsApp commerce.", "pitch_angle": "Spell Growth does R&D-based marketing. COMAI is a data-driven WhatsApp commerce tool.", "source": "manual_research"},
    {"agency_name": "The Yellowtail Studio", "country": "India", "city": "Surat, Gujarat", "agency_type": "Creative and Marketing Agency", "clients": "Fashion, beauty, jewelry, home decor brands", "decision_maker": "Sheetal", "decision_maker_role": "Founder", "email": "sheetal@theyellowtailstudio.com", "phone": "+91-7827571035", "linkedin": "https://linkedin.com/in/sheetal23patil", "contactability": "HIGH", "services": ["Branding", "Social Media", "Content", "Influencer", "SEO", "Website Design"], "tier": "C", "client_access_score": 55, "comai_fit_score": 65, "final_score": 60, "why_this_agency": "Fashion/beauty/jewelry focus. Myntra Studio management.", "comai_fit": "Fashion/beauty brands need WhatsApp commerce.", "pitch_angle": "Yellowtail Studio serves fashion/beauty brands. COMAI adds WhatsApp commerce.", "source": "manual_research"},
    {"agency_name": "Surge Lion Media", "country": "India", "agency_type": "AI-Led Growth Agency", "clients": "D2C brands (beauty, skincare)", "contactability": "MEDIUM", "services": ["Meta Ads", "Google Ads", "AI Chatbot", "CRO", "Creative Strategy", "Retention Marketing"], "tier": "C", "client_access_score": 55, "comai_fit_score": 70, "final_score": 62, "why_this_agency": "AI-led growth. 10000% ROI in retention marketing. 5x ROAS.", "comai_fit": "Already does AI chatbot + retention. COMAI replaces their chatbot with better commerce.", "pitch_angle": "Surge Lion does AI chatbot + retention. COMAI is better WhatsApp commerce AI.", "source": "manual_research"},
]

async def main():
    conn = await asyncpg.connect(host='127.0.0.1', port=5432, database='beacon', user='beacon', password='beacon_password')
    inserted = 0
    for lead in EXTRA_LEADS:
        lead['id'] = str(uuid.uuid4())
        lead['status'] = 'NEW'
        lead['outreach_sent'] = False
        lead['response_received'] = False
        lead['meeting_scheduled'] = False
        lead['partner_converted'] = False
        for key in ['notable_clients', 'notable_results', 'decision_makers', 'services', 'certifications', 'tags']:
            lead[key] = json.dumps(lead.get(key) or [])
        lead['evidence'] = json.dumps({})
        try:
            await conn.execute(
                '''INSERT INTO partner_leads (id, agency_name, agency_url, country, city, agency_type, employees, founded, clients, client_count, revenue_generated, revenue_managed, notable_clients, notable_results, decision_maker, decision_maker_role, decision_makers, email, phone, linkedin, contactability, services, certifications, tier, client_access_score, comai_fit_score, partner_intent, final_score, why_this_agency, comai_fit, pitch_angle, source, status, outreach_sent, response_received, meeting_scheduled, partner_converted, evidence, tags) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15,$16,$17::jsonb,$18,$19,$20,$21,$22::jsonb,$23::jsonb,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38::jsonb,$39::jsonb)''',
                lead['id'], lead['agency_name'], lead.get('agency_url'), lead.get('country'),
                lead.get('city'), lead.get('agency_type'), lead.get('employees'), lead.get('founded'),
                lead.get('clients'), lead.get('client_count'), lead.get('revenue_generated'),
                lead.get('revenue_managed'), lead['notable_clients'], lead['notable_results'],
                lead.get('decision_maker'), lead.get('decision_maker_role'), lead['decision_makers'],
                lead.get('email'), lead.get('phone'), lead.get('linkedin'), lead.get('contactability'),
                lead['services'], lead['certifications'], lead.get('tier'),
                lead.get('client_access_score'), lead.get('comai_fit_score'),
                lead.get('partner_intent'), lead.get('final_score'),
                lead.get('why_this_agency'), lead.get('comai_fit'), lead.get('pitch_angle'),
                lead.get('source'), lead['status'], lead['outreach_sent'],
                lead['response_received'], lead['meeting_scheduled'],
                lead['partner_converted'], lead['evidence'], lead['tags']
            )
            inserted += 1
            print(f'  INSERTED: {lead["agency_name"]} (Tier {lead.get("tier", "C")})')
        except Exception as e:
            print(f'  ERROR: {lead["agency_name"]} - {e}')
    await conn.close()
    print(f'\n  Total inserted: {inserted}/{len(EXTRA_LEADS)}')

asyncio.run(main())
