"""Insert new mega leads for COMAI B2B with real phone numbers"""
import asyncio
import asyncpg

DB_DSN = "postgresql://beacon:beacon_password@127.0.0.1:5432/beacon"

LEADS = [
    # ShivOhm Infotech - D2C Performance Growth Agency, Ahmedabad
    {
        "agency_name": "ShivOhm Infotech",
        "agency_url": "https://shivohminfotech.com",
        "city": "Ahmedabad",
        "country": "India",
        "agency_type": "D2C Performance Growth Agency",
        "employees": "5-10",
        "description": "Founder-led D2C performance growth agency. Shopify-first brands. Meta Ads, Google Ads, creative testing, CRO, retention, AI-powered reporting.",
        "decision_maker": "Manav",
        "decision_maker_role": "Founder",
        "email": "manav@shivohminfotech.com",
        "phone": "+919408377432",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Founder-led agency, Shopify specialists, strong D2C track record. WhatsApp flows for retention.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # RankMyShopify - Shopify-only marketing agency since 2009, Mohali
    {
        "agency_name": "RankMyShopify",
        "agency_url": "https://rankmyshopify.com",
        "city": "Mohali",
        "country": "India",
        "agency_type": "Shopify Marketing Agency",
        "employees": "50-100",
        "description": "Shopify-only marketing agency since 2009. 60+ team, 500+ stores scaled, ₹500Cr+ tracked client revenue. Shopify expert partners.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "+919888923755",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Established Shopify-only agency, massive scale, deep expertise. Perfect partner for WhatsApp commerce.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 85,
    },
    # Atlas Forge - D2C Growth Agency, Bangalore
    {
        "agency_name": "Atlas Forge",
        "agency_url": "https://atlas-forge-global.lovable.app",
        "city": "Bangalore",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "5-10",
        "description": "Performance-driven D2C growth agency. Shopify D2C, marketplace management, performance marketing, international expansion.",
        "decision_maker": "Talal Aziz",
        "decision_maker_role": "Head of Performance & D2C Platforms",
        "email": "talalaziz00@gmail.com",
        "phone": "+918789845398",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "D2C growth agency, Shopify + marketplace specialist.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # Skale10x - Amazon & D2C Growth Agency, Hyderabad
    {
        "agency_name": "Skale10x",
        "agency_url": "https://skale10x.com",
        "city": "Hyderabad",
        "country": "India",
        "agency_type": "Amazon & D2C Growth Agency",
        "employees": "10-20",
        "description": "India's #1 Amazon & D2C Growth Agency. 8 years, 200+ brands, ₹500Cr+ client revenue. Amazon PPC, Flipkart, Shopify D2C, performance marketing.",
        "decision_maker": "Pranay Mudigonda",
        "decision_maker_role": "Founder & CEO",
        "email": "pranay.m@skale10x.com",
        "phone": "+918328593607",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Established 8-year agency, 200+ brands, deep ecommerce expertise. Shopify D2C specialist.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 85,
    },
    # 500.Marketing - D2C Growth Agency, Greater Noida
    {
        "agency_name": "500.Marketing",
        "agency_url": "https://500.marketing",
        "city": "Greater Noida",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "5-10",
        "description": "Google Ads, SEO & AI Automation Agency. D2C growth agency. Shopify development, custom web apps, AI automation.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "contact@500.marketing",
        "phone": "+918081676287",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "D2C growth agency, Shopify dev, AI automation.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # Performaks - D2C Performance Marketing, Delhi
    {
        "agency_name": "Performaks",
        "agency_url": "https://performaks.com",
        "city": "New Delhi",
        "country": "India",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "10-20",
        "description": "India's Leading D2C Performance Marketing Agency. Ecommerce SEO, Shopify development, custom web solutions, API solutions.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "growth@performaks.com",
        "phone": "+919560068999",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Full-stack D2C agency, Shopify dev, strong performance marketing.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 85,
    },
    # Fast Grow Technology - E-Commerce Growth Agency, Rajkot
    {
        "agency_name": "Fast Grow Technology",
        "agency_url": "https://fastgrow.net",
        "city": "Rajkot",
        "country": "India",
        "agency_type": "E-Commerce Growth Agency",
        "employees": "10-20",
        "description": "India's first AI-powered e-commerce agency. Amazon, Flipkart, Myntra, Shopify, Blinkit, Meesho. Shopify & WooCommerce development.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "+919104322040",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "E-commerce agency, Shopify dev, multi-marketplace.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # High Commerce - Ecommerce Growth Agency, Delhi
    {
        "agency_name": "High Commerce",
        "agency_url": "https://highcommerce.in",
        "city": "Delhi",
        "country": "India",
        "agency_type": "Ecommerce Growth Agency",
        "employees": "5-10",
        "description": "Results-driven ecommerce growth agency. Shopify store design & development, marketplace management, ads, inventory.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "official@highcommerce.in",
        "phone": "+919953470502",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Ecommerce agency, Shopify specialists.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # DigiBrood - Ecommerce Growth Agency
    {
        "agency_name": "DigiBrood",
        "agency_url": "https://digibrood.com",
        "city": "India",
        "country": "India",
        "agency_type": "Ecommerce Growth Agency",
        "employees": "10-20",
        "description": "E-commerce growth agency. Shopify Partner, Meta Business Partner, Google Premier Partner. 150+ brands scaled. WhatsApp, CRO & retention.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "+918777571887",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Shopify Partner + Meta + Google partners, 150+ brands, WhatsApp expertise.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 85,
    },
    # ScaleInbox - D2C Fashion Growth Agency, New Delhi
    {
        "agency_name": "ScaleInbox",
        "agency_url": "https://scaleinbox.in",
        "city": "New Delhi",
        "country": "India",
        "agency_type": "D2C Fashion Growth Agency",
        "employees": "5-10",
        "description": "D2C fashion focused performance marketing and brand building agency. Meta ads, funnels, growth systems for fashion brands.",
        "decision_maker": "Shubham",
        "decision_maker_role": "Founder",
        "email": "shubhambuilds.co@gmail.com",
        "phone": "+919211489977",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "D2C fashion specialist, performance marketing.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # Influenzé - UGC/Content Agency, Kolkata
    {
        "agency_name": "Influenzé",
        "agency_url": "",
        "city": "Kolkata",
        "country": "India",
        "agency_type": "UGC/Content Agency",
        "employees": "1-5",
        "description": "UGC and influencer marketing agency. 75+ brands served. Content creation for D2C brands. Also runs Publicize growth agency.",
        "decision_maker": "Ritobrataa Sen",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "+919073709986",
        "linkedin": "https://linkedin.com/in/ritobrataasen12",
        "tier": "C",
        "why_this_agency": "UGC/content agency, content partner for D2C brands.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 15,
        "final_score": 60,
    },
    # Neuroid - D2C Growth Agency, New Delhi
    {
        "agency_name": "Neuroid",
        "agency_url": "",
        "city": "New Delhi",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "10-20",
        "description": "eCommerce growth marketing agency. DTC brands. 70+ brands, $17M+ revenue generated. Meta, Google, Snapchat ads. CRO & retention.",
        "decision_maker": "Laksh Sehgal",
        "decision_maker_role": "Founder",
        "email": "laksh@neuroidmedia.com",
        "phone": "",
        "linkedin": "https://linkedin.com/in/lakshsehgal",
        "tier": "A",
        "why_this_agency": "Established D2C growth agency, 70+ brands, strong case studies.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 20,
        "final_score": 78,
    },
    # AdyCircle - D2C Growth Agency, Ahmedabad
    {
        "agency_name": "AdyCircle",
        "agency_url": "https://www.adycircle.com",
        "city": "Ahmedabad",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "10-20",
        "description": "Full stack D2C growth agency. Meta, Google ads, deep technical SEO, WhatsApp recovery flows. Skincare, beauty, fashion, health brands.",
        "decision_maker": "Lokendra",
        "decision_maker_role": "Founder & CEO",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Full-stack D2C agency, WhatsApp flows, strong positioning.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 70,
    },
    # Founder Cartel - D2C Digital Marketing, Lucknow
    {
        "agency_name": "Founder Cartel",
        "agency_url": "https://foundercartel.com",
        "city": "Lucknow",
        "country": "India",
        "agency_type": "D2C Digital Marketing Agency",
        "employees": "5-10",
        "description": "Full-funnel digital marketing agency for DTC brands. Meta & Google Ads, WhatsApp automation, content creation, Shopify optimization.",
        "decision_maker": "Divyansh",
        "decision_maker_role": "Founder",
        "email": "foundercartel@gmail.com",
        "phone": "+918005319313",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Full-funnel D2C agency, WhatsApp automation, Shopify optimization.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # ROI Hunt - Ecommerce Growth Agency
    {
        "agency_name": "ROI Hunt",
        "agency_url": "https://roihuntecom.com",
        "city": "India",
        "country": "India",
        "agency_type": "Ecommerce Growth Agency",
        "employees": "10-20",
        "description": "Profit-led D2C growth partner. 200+ brands, ₹500Cr+ revenue. Multi-channel: Meta, Google, Marketplaces, Email, WhatsApp.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Established D2C growth partner, 200+ brands, multi-channel including WhatsApp.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 70,
    },
    # Studio APS - D2C Growth Agency
    {
        "agency_name": "Studio APS",
        "agency_url": "https://studioaps.in",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "5-10",
        "description": "D2C brand growth agency. Paid advertising, creatives, web design, SEO, social media, CRO. Led by Harsh.",
        "decision_maker": "Harsh",
        "decision_maker_role": "Founder",
        "email": "info@studioaps.in",
        "phone": "",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "D2C growth agency, CRO, web design.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 20,
        "final_score": 65,
    },
    # Kreative & Co - Marketing, Design & Tech Agency
    {
        "agency_name": "Kreative & Co",
        "agency_url": "https://kreativee.com",
        "city": "India",
        "country": "India",
        "agency_type": "Marketing, Design & Tech Agency",
        "employees": "20-50",
        "description": "Marketing, Design & Tech Agency. $100M+ generated for D2C and ecommerce brands in 2025. Rebranded from Kreative Digitals.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Large scale D2C agency, $100M+ revenue generated.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 20,
        "final_score": 70,
    },
    # Entangled Marketing - D2C Growth Consultancy
    {
        "agency_name": "Entangled Marketing",
        "agency_url": "https://entangled.marketing",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Growth Consultancy",
        "employees": "1-5",
        "description": "D2C Growth Consultancy by Vasundhara Jain. 4+ years D2C, 6 years FMCG (P&G, Godrej). 20+ brands. Brand strategy + performance marketing.",
        "decision_maker": "Vasundhara Jain",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "C",
        "why_this_agency": "Solo consultant, strong FMCG background but smaller scale.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 15,
        "final_score": 45,
    },
]

async def insert():
    conn = await asyncpg.connect(DB_DSN)
    try:
        inserted = 0
        skipped = 0
        for lead in LEADS:
            # Check if already exists
            exists = await conn.fetchval(
                "SELECT id FROM partner_leads WHERE agency_name = $1",
                lead["agency_name"]
            )
            if exists:
                skipped += 1
                continue
            await conn.execute(
                """INSERT INTO partner_leads 
                   (agency_name, agency_url, city, country, agency_type, employees,
                    description, decision_maker, decision_maker_role, email, phone, linkedin,
                    tier, why_this_agency, contactability, status, lead_source,
                    client_access_score, comai_fit_score, final_score)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)""",
                lead["agency_name"], lead["agency_url"], lead["city"],
                lead["country"], lead["agency_type"], lead["employees"],
                lead["description"], lead["decision_maker"], lead["decision_maker_role"],
                lead["email"], lead["phone"], lead["linkedin"],
                lead["tier"], lead["why_this_agency"], lead["contactability"],
                lead["status"], lead["lead_source"],
                lead["client_access_score"], lead["comai_fit_score"], lead["final_score"],
            )
            inserted += 1
            print(f"  INSERTED: {lead['agency_name']} | {lead['phone'] or 'no phone'} | {lead['email'] or 'no email'}")
        
        total = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b'")
        with_phone = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND phone != '' AND phone IS NOT NULL")
        with_email = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND email != '' AND email IS NOT NULL")
        
        print(f"\nRESULTS: {inserted} inserted, {skipped} skipped (duplicates)")
        print(f"TOTAL comai_b2b: {total} leads | {with_phone} with phone | {with_email} with email")
    finally:
        await conn.close()

asyncio.run(insert())
