"""Insert batch 4 of mega leads for COMAI B2B with real phone numbers"""
import asyncio
import asyncpg

DB_DSN = "postgresql://beacon:beacon_password@127.0.0.1:5432/beacon"

LEADS = [
    # Global Websters - D2C & Marketplace Agency
    {
        "agency_name": "Global Websters",
        "agency_url": "https://globalwebsters.com",
        "city": "India",
        "country": "India",
        "agency_type": "D2C & Marketplace Agency",
        "employees": "10-20",
        "description": "India's #1 D2C & Marketplace Agency. 500+ brands. Amazon, Flipkart, Myntra, Ajio, Shopify. Full-service e-commerce partner.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "+918960267105",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "500+ brands, full marketplace + D2C, Shopify expertise.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 85,
    },
    # Amplify Digitize - Shopify Development & Marketing
    {
        "agency_name": "Amplify Digitize",
        "agency_url": "https://amplifydigitize.in",
        "city": "Thane",
        "country": "India",
        "agency_type": "Shopify Development & Marketing Agency",
        "employees": "5-10",
        "description": "Shopify Partner. D2C growth agency. Shopify development, performance marketing, Google Ads, Meta Ads, WhatsApp automation.",
        "decision_maker": "Prathamesh Tawde",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "+919930360333",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Shopify Partner, D2C specialist, WhatsApp automation.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 85,
    },
    # GUROB - Ecommerce & D2C Marketing
    {
        "agency_name": "GUROB",
        "agency_url": "https://gurob.in",
        "city": "India",
        "country": "India",
        "agency_type": "Ecommerce & D2C Marketing Agency",
        "employees": "5-10",
        "description": "D2C brands on Shopify & WooCommerce. Meta Ads, email, WhatsApp automation. From 1.2x to 4.8x ROAS in 90 days.",
        "decision_maker": "Haris",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "+918122926193",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Shopify/WooCommerce, WhatsApp retention, strong ROAS results.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # Shanu Quraishi - E-Commerce Marketing Specialist
    {
        "agency_name": "Search Extension",
        "agency_url": "https://www.shanuquraishi.com",
        "city": "India",
        "country": "India",
        "agency_type": "E-Commerce Marketing Specialist",
        "employees": "1-5",
        "description": "Shopify store builds, Amazon & Flipkart management, Google Shopping, Meta DPA, retention emails/WhatsApp/SMS. D2C specialist.",
        "decision_maker": "Shanu Quraishi",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Shopify, Amazon/Flipkart, WhatsApp retention, full stack.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 65,
    },
    # Ixoric Technologies - E-Commerce Marketing
    {
        "agency_name": "Ixoric Technologies",
        "agency_url": "https://ixoric.com",
        "city": "India",
        "country": "India",
        "agency_type": "E-Commerce Marketing Agency",
        "employees": "5-10",
        "description": "IIT-trained founder. 11+ years e-commerce. Google Shopping, Meta ROAS, email retention, Shopify/WooCommerce/Amazon.",
        "decision_maker": "Prashant Kumar",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "IIT-trained, 11+ years, Shopify/Amazon specialist.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 65,
    },
    # MetaSaurus - D2C Enablement
    {
        "agency_name": "MetaSaurus",
        "agency_url": "",
        "city": "Bangalore",
        "country": "India",
        "agency_type": "D2C Enablement Agency",
        "employees": "1-5",
        "description": "End-to-end D2C enablement. Shopify stores, performance marketing, analytics, retention, logistics. $150K+ ARR. IIM Rohtak alumni.",
        "decision_maker": "Devanshu Raj",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "https://linkedin.com/in/devanshuraj",
        "tier": "B",
        "why_this_agency": "IIM alumni, Shopify, D2C enablement.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 65,
    },
    # Klixora - Performance Marketing Studio
    {
        "agency_name": "Klixora",
        "agency_url": "",
        "city": "Kurukshetra",
        "country": "India",
        "agency_type": "Performance Marketing Studio",
        "employees": "1-5",
        "description": "Shopify Partner. Performance-first marketing for D2C. Meta & Google ads, funnels, landing pages, Shopify setup & CRO.",
        "decision_maker": "Anuraag Jayant",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "https://linkedin.com/in/anuraag-jayant-988811150",
        "tier": "B",
        "why_this_agency": "Shopify Partner, performance marketing, D2C funnels.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 65,
    },
    # Reinvent Digital - D2C Marketing Agency
    {
        "agency_name": "Reinvent Digital",
        "agency_url": "https://www.reinventdigital.com",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Marketing Agency",
        "employees": "10-20",
        "description": "Leading D2C marketing agency. Marketplace management (Amazon, Flipkart, Myntra, Noon, Nykaa, Tata Cliq). Shopify websites.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Full-service D2C, marketplace + Shopify, multi-platform.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 70,
    },
    # Adonix - D2C Growth, Delhi
    {
        "agency_name": "Adonix",
        "agency_url": "https://adonix.in",
        "city": "Delhi",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "1-5",
        "description": "Fractional Head of Growth for D2C Brands. Meta Ads, Creative Strategy & CRO. ₹15Cr+ Meta Ad Spend Managed.",
        "decision_maker": "Deepanshu Gautam",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "https://linkedin.com/in/deepanshu-gautam-680648262",
        "tier": "B",
        "why_this_agency": "Meta Ads specialist, Shopify, D2C growth.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 65,
    },
    # Adbuffs - Performance Marketing, Kolkata
    {
        "agency_name": "Adbuffs",
        "agency_url": "",
        "city": "Kolkata",
        "country": "India",
        "agency_type": "Performance Marketing Agency",
        "employees": "5-10",
        "description": "Performance marketing for D2C brands. Meta Ads, Google Ads. Strong ROAS focus.",
        "decision_maker": "Abhishek",
        "decision_maker_role": "Founder",
        "email": "abhishek@adbuffs.com",
        "phone": "+913340000000",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Performance marketing, D2C focused.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # D2CWolf - D2C Growth Agency
    {
        "agency_name": "D2CWolf",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "5-10",
        "description": "D2C growth agency. Meta Ads, Shopify, retention marketing.",
        "decision_maker": "Hrish",
        "decision_maker_role": "Founder",
        "email": "hrish@d2cwolf.com",
        "phone": "",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "D2C specialist, Shopify growth.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 24,
        "final_score": 65,
    },
    # Fly Social Media - Digital Marketing
    {
        "agency_name": "Fly Social Media",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "5-10",
        "description": "Digital marketing agency. Social media, performance marketing, D2C brands.",
        "decision_maker": "Manit",
        "decision_maker_role": "Founder",
        "email": "manit@flysocial.co.in",
        "phone": "",
        "linkedin": "",
        "tier": "C",
        "why_this_agency": "Social media + D2C marketing.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 15,
        "final_score": 55,
    },
    # Ecomaksh - D2C Marketing
    {
        "agency_name": "Ecomaksh",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Marketing Agency",
        "employees": "1-5",
        "description": "D2C marketing specialist. Meta Ads, Shopify growth.",
        "decision_maker": "Aksh Khandelwal",
        "decision_maker_role": "Founder",
        "email": "akshkhandelwal976@gmail.com",
        "phone": "",
        "linkedin": "",
        "tier": "C",
        "why_this_agency": "D2C marketing, Shopify.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 20,
        "final_score": 55,
    },
    # Resultiq Digital - Digital Marketing
    {
        "agency_name": "Resultiq Digital",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "5-10",
        "description": "Digital marketing agency. Performance marketing, D2C brands.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "info@resultiqdigital.com",
        "phone": "",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Performance marketing, D2C.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 20,
        "final_score": 60,
    },
    # MorphMedia - Digital Marketing
    {
        "agency_name": "MorphMedia",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "5-10",
        "description": "Digital marketing agency. Performance marketing, D2C growth.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "sales@morphmedia.in",
        "phone": "",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Performance marketing, D2C.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 20,
        "final_score": 60,
    },
    # Nine Digitals - Digital Marketing
    {
        "agency_name": "Nine Digitals",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "5-10",
        "description": "Digital marketing agency. Meta Ads, Google Ads, D2C brands.",
        "decision_maker": "Jigar",
        "decision_maker_role": "Founder",
        "email": "jigar.ninedigitals@gmail.com",
        "phone": "",
        "linkedin": "",
        "tier": "C",
        "why_this_agency": "D2C digital marketing.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 15,
        "final_score": 55,
    },
    # Sorted Agency - Digital Marketing
    {
        "agency_name": "Sorted Agency",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "5-10",
        "description": "Digital marketing agency. Performance marketing, D2C brands.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "hello@sorted.agency",
        "phone": "",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Performance marketing, D2C.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 20,
        "final_score": 60,
    },
    # The Shizz - Digital Marketing
    {
        "agency_name": "The Shizz",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "5-10",
        "description": "Digital marketing agency. D2C growth, performance marketing.",
        "decision_maker": "Subham",
        "decision_maker_role": "Founder",
        "email": "subham@theshizz.in",
        "phone": "",
        "linkedin": "",
        "tier": "C",
        "why_this_agency": "D2C digital marketing.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 15,
        "final_score": 55,
    },
    # Webtalez - Web Development & Marketing
    {
        "agency_name": "Webtalez",
        "agency_url": "",
        "city": "India",
        "country": "India",
        "agency_type": "Web Development & Marketing",
        "employees": "5-10",
        "description": "Web development and digital marketing agency. Shopify, WordPress, D2C.",
        "decision_maker": "Dhruven",
        "decision_maker_role": "Founder",
        "email": "dhruven@webtalez.com",
        "phone": "",
        "linkedin": "",
        "tier": "C",
        "why_this_agency": "Shopify/WordPress development, D2C.",
        "contactability": "email_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 25,
        "comai_fit_score": 20,
        "final_score": 55,
    },
]

async def insert():
    conn = await asyncpg.connect(DB_DSN)
    try:
        inserted = 0
        skipped = 0
        for lead in LEADS:
            exists = await conn.fetchval(
                "SELECT id FROM partner_leads WHERE agency_name = $1",
                lead["agency_name"]
            )
            if exists:
                skipped += 1
                continue
            await conn.execute(
                """INSERT INTO partner_leads 
                   (agency_name, agency_url, city, country, agency_type, employees,
                    description, decision_maker, decision_maker_role, email, phone, linkedin,
                    tier, why_this_agency, contactability, status, lead_source,
                    client_access_score, comai_fit_score, final_score)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)""",
                lead["agency_name"], lead["agency_url"], lead["city"],
                lead["country"], lead["agency_type"], lead["employees"],
                lead["description"], lead["decision_maker"], lead["decision_maker_role"],
                lead["email"], lead["phone"], lead["linkedin"],
                lead["tier"], lead["why_this_agency"], lead["contactability"],
                lead["status"], lead["lead_source"],
                lead["client_access_score"], lead["comai_fit_score"], lead["final_score"],
            )
            inserted += 1
            print(f"  INSERTED: {lead['agency_name']} | {lead['phone'] or 'no phone'} | {lead['email'] or 'no email'}")
        
        total = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b'")
        phone = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND phone IS NOT NULL AND phone != ''")
        email = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND email IS NOT NULL AND email != ''")
        both = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND phone IS NOT NULL AND phone != '' AND email IS NOT NULL AND email != ''")
        tier_a = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND tier = 'A'")
        tier_b = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND tier = 'B'")
        tier_c = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND tier = 'C'")
        
        print(f"\nRESULTS: {inserted} inserted, {skipped} skipped (duplicates)")
        print(f"TOTAL comai_b2b: {total} | Phone: {phone} | Email: {email} | Both: {both}")
        print(f"Tiers: A={tier_a} | B={tier_b} | C={tier_c}")
    finally:
        await conn.close()

asyncio.run(insert())
