"""Insert high-intent agency leads with phone numbers."""
import json
import uuid
import asyncpg
import asyncio

LEADS = [
    {
        "agency_name": "A3 Mediacom",
        "agency_url": "https://a3mediacom.in",
        "country": "India",
        "city": "Gurugram",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "10-20",
        "founded": 2023,
        "clients": "20+ brands scaled, $50M+ revenue generated",
        "client_count": 20,
        "revenue_generated": "₹100Cr+ tracked D2C revenue",
        "decision_maker": "Aditya Jain",
        "decision_maker_role": "Founder",
        "email": "aditya@a3mediacom.in",
        "linkedin": "https://linkedin.com/in/aditya-jain1",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Amazon Ads", "Full-Funnel Growth", "Retention"],
        "tier": "A",
        "client_access_score": 70,
        "comai_fit_score": 80,
        "final_score": 75,
        "why_this_agency": "$50M+ D2C revenue generated. 20+ brands. Fashion, Beauty, Nutraceuticals, Home Decor. 20+ person team.",
        "comai_fit": "D2C brands doing $50K-$1M/month. Perfect for WhatsApp commerce.",
        "pitch_angle": "A3 Mediacom generates $50M+ for D2C brands. COMAI adds WhatsApp commerce layer.",
        "source": "manual_research",
    },
    {
        "agency_name": "Adbuffs",
        "agency_url": "https://adbuffs.com",
        "country": "India",
        "city": "Kolkata",
        "agency_type": "eCommerce Growth Agency",
        "employees": "100-150",
        "founded": 2019,
        "clients": "250+ brands scaled including GIVA, Thriveco, Renee Cosmetics, Rage Coffee",
        "client_count": 250,
        "revenue_managed": "₹750+ crores ad spend managed",
        "decision_maker": "Abhishek M.",
        "decision_maker_role": "Co-Founder",
        "linkedin": "https://linkedin.com/in/abhishek-maity-adbuffs",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Amazon Ads", "TikTok Ads", "Snapchat Ads", "Pinterest Ads", "Server-Side Tracking"],
        "tier": "A",
        "client_access_score": 80,
        "comai_fit_score": 75,
        "final_score": 78,
        "why_this_agency": "250+ brands. ₹750+ crores ad spend. Custom attribution systems. 100+ person team. GIVA, Renee, Rage Coffee.",
        "comai_fit": "Massive client base. Enterprise-level D2C brands need WhatsApp commerce.",
        "pitch_angle": "Adbuffs manages ₹750Cr+ ad spend for 250+ D2C brands. COMAI adds WhatsApp commerce to their stack.",
        "source": "manual_research",
    },
    {
        "agency_name": "Marketing Lab",
        "agency_url": "https://marketinglab.in",
        "country": "India",
        "city": "Kolkata",
        "agency_type": "Performance Marketing Agency",
        "employees": "70-80",
        "founded": 2019,
        "clients": "54 D2C brands including 21 Shark Tank India brands",
        "client_count": 54,
        "decision_maker": "Mintu Jha",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/mintu-jha",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Performance Marketing", "Creative Strategy"],
        "tier": "A",
        "client_access_score": 70,
        "comai_fit_score": 80,
        "final_score": 75,
        "why_this_agency": "54 D2C brands. 21 Shark Tank India brands. 70-80 employees. 9 figure/month brands.",
        "comai_fit": "Shark Tank brands need WhatsApp commerce. Massive distribution.",
        "pitch_angle": "Marketing Lab scales 21 Shark Tank brands. COMAI adds WhatsApp commerce.",
        "source": "manual_research",
    },
    {
        "agency_name": "Fly Social Media",
        "agency_url": "https://flysocial.co.in",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "F&B D2C Growth Agency",
        "employees": "1-10",
        "founded": 2020,
        "clients": "53+ F&B D2C brands",
        "client_count": 53,
        "revenue_generated": "₹96.2CR+ generated for clients",
        "decision_maker": "Manit Ahuja",
        "decision_maker_role": "Founder",
        "email": "manit@flysocial.co.in",
        "linkedin": "https://linkedin.com/in/manitahujafsm",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "SEO", "Website Development", "Social Media"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "final_score": 70,
        "why_this_agency": "53+ F&B brands. ₹96.2CR+ generated. Specialist in food/beverage D2C.",
        "comai_fit": "F&B brands need WhatsApp commerce for repeat purchases and replenishment.",
        "pitch_angle": "Fly Social scales 53+ F&B brands. COMAI drives repeat purchases via WhatsApp.",
        "source": "manual_research",
    },
    {
        "agency_name": "1% Media",
        "agency_url": "https://1percentmedia.in",
        "country": "India",
        "city": "Ahmedabad",
        "agency_type": "Performance Marketing Agency",
        "employees": "1-10",
        "founded": 2025,
        "clients": "50+ brands across India, USA, Canada",
        "client_count": 50,
        "revenue_generated": "$1.2M+ revenue generated",
        "decision_maker": "Vir Singh Chavda",
        "decision_maker_role": "Founder",
        "email": "virsinghchavda@gmail.com",
        "phone": "+91-7990377891",
        "linkedin": "https://linkedin.com/in/vir-singh-chavda-a61972256",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Funnel Optimization", "eCommerce Growth"],
        "tier": "B",
        "client_access_score": 60,
        "comai_fit_score": 75,
        "final_score": 67,
        "why_this_agency": "50+ brands. $1.2M+ revenue. 4x+ ROAS. Limited clients, maximum attention.",
        "comai_fit": "D2C brands need WhatsApp commerce. Founder-led, high-touch agency.",
        "pitch_angle": "1% Media scales 50+ D2C brands. COMAI adds WhatsApp commerce layer.",
        "source": "manual_research",
    },
    {
        "agency_name": "Adonix",
        "agency_url": "https://adonix.in",
        "country": "India",
        "city": "Delhi",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "1-10",
        "founded": 2021,
        "clients": "D2C brands doing ₹5-20L/month",
        "revenue_managed": "₹15Cr+ Meta Ad Spend Managed",
        "decision_maker": "Deepanshu Gautam",
        "decision_maker_role": "Founder & CEO",
        "linkedin": "https://linkedin.com/in/deepanshu-gautam-680648262",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Creative Strategy", "CRO", "Shopify Optimization"],
        "tier": "B",
        "client_access_score": 60,
        "comai_fit_score": 75,
        "final_score": 67,
        "why_this_agency": "₹15Cr+ Meta ad spend. Fractional Head of Growth for D2C brands. Shopify-focused.",
        "comai_fit": "Shopify D2C brands need WhatsApp commerce.",
        "pitch_angle": "Adonix manages ₹15Cr+ Meta spend for Shopify D2C brands. COMAI installs on Shopify.",
        "source": "manual_research",
    },
    {
        "agency_name": "Raasaa D2C",
        "agency_url": "https://raasaa.in",
        "country": "India",
        "city": "Noida",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "1-10",
        "founded": 2022,
        "clients": "50+ crore portfolio managed",
        "revenue_managed": "50+ crores portfolio",
        "decision_maker": "Avishek Podder",
        "decision_maker_role": "Founder",
        "phone": "+91-9987233380",
        "linkedin": "https://linkedin.com/in/avishek-podder-464912279",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Performance Marketing", "Creative Strategy"],
        "tier": "B",
        "client_access_score": 60,
        "comai_fit_score": 70,
        "final_score": 65,
        "why_this_agency": "50+ crore portfolio. Clothing brand specialist. Film industry background.",
        "comai_fit": "Fashion/clothing D2C brands need WhatsApp commerce.",
        "pitch_angle": "Raasaa manages 50+ crore portfolio. COMAI adds WhatsApp commerce for fashion brands.",
        "source": "manual_research",
    },
    {
        "agency_name": "Klixora",
        "agency_url": "https://klixora.com",
        "country": "India",
        "city": "Kurukshetra",
        "agency_type": "Performance Marketing Studio",
        "employees": "1-10",
        "founded": 2022,
        "clients": "D2C brands in skincare, food, fashion, health",
        "decision_maker": "Anuraag Jayant",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/anuraag-jayant-988811150",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Funnels", "Landing Pages", "Shopify CRO", "WhatsApp Automation", "Email Automation"],
        "tier": "C",
        "client_access_score": 55,
        "comai_fit_score": 80,
        "final_score": 67,
        "why_this_agency": "Shopify Partner. Does WhatsApp + Email automation. Performance-first studio.",
        "comai_fit": "Already does WhatsApp automation. COMAI replaces manual work.",
        "pitch_angle": "Klixora does WhatsApp automation manually. COMAI automates with AI chatbot + commerce.",
        "source": "manual_research",
    },
    {
        "agency_name": "Performance Crafters",
        "agency_url": "https://performancecrafters.com",
        "country": "India",
        "city": "Delhi",
        "agency_type": "Performance Marketing Agency",
        "employees": "1-10",
        "founded": 2021,
        "clients": "40+ brands across fashion, beauty, education, food",
        "client_count": 40,
        "decision_maker": "Poonam Gangwal",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/poonam-gangwal-55134393",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Amazon Ads", "Criteo", "Data Analytics", "CRO"],
        "tier": "C",
        "client_access_score": 60,
        "comai_fit_score": 70,
        "final_score": 65,
        "why_this_agency": "40+ brands. 14+ years experience. Google Shopping, Amazon, Meta specialist.",
        "comai_fit": "Fashion/beauty/food brands need WhatsApp commerce.",
        "pitch_angle": "Performance Crafters scales 40+ brands. COMAI adds WhatsApp commerce.",
        "source": "manual_research",
    },
    {
        "agency_name": "Webtalez",
        "agency_url": "https://webtalez.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Performance Marketing Agency",
        "employees": "1-10",
        "founded": 2021,
        "clients": "eCommerce brands",
        "decision_maker": "Dhruven Turakhia",
        "decision_maker_role": "Founder",
        "email": "dhruven@webtalez.com",
        "linkedin": "https://linkedin.com/in/tdhruven",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Performance Marketing", "Retention", "CRO"],
        "tier": "C",
        "client_access_score": 55,
        "comai_fit_score": 70,
        "final_score": 62,
        "why_this_agency": "10+ years performance marketing. Revenue-first model. Retention focus.",
        "comai_fit": "Retention-focused agency. WhatsApp commerce drives retention.",
        "pitch_angle": "Webtalez focuses on retention. COMAI drives repeat purchases via WhatsApp.",
        "source": "manual_research",
    },
    {
        "agency_name": "Adscrey",
        "agency_url": "https://adscrey.com",
        "country": "India",
        "city": "Gurugram",
        "agency_type": "Performance Marketing Agency",
        "employees": "20-30",
        "founded": 2020,
        "clients": "200+ brands scaled",
        "client_count": 200,
        "revenue_managed": "45000+ ad campaigns optimized",
        "decision_maker": "Shivam Kumar Soni",
        "decision_maker_role": "Co-Founder & Business Head",
        "linkedin": "https://linkedin.com/in/digitalmarketing-shivam-kumar",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "CRO", "eCommerce Marketing", "Branding"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 70,
        "final_score": 67,
        "why_this_agency": "200+ brands. 45000+ campaigns. 4.5+ ROAS. Google, SEMrush, Meta certified.",
        "comai_fit": "200+ brands need WhatsApp commerce.",
        "pitch_angle": "Adscrey scales 200+ brands. COMAI adds WhatsApp commerce layer.",
        "source": "manual_research",
    },
    {
        "agency_name": "Ecomking Media",
        "agency_url": "https://ecomkingmedia.com",
        "country": "India",
        "city": "Hojai",
        "agency_type": "Shopify Development Agency",
        "employees": "8",
        "clients": "1500+ stores built, $75M+ client revenue",
        "client_count": 1500,
        "decision_maker": "Rahul Jain",
        "decision_maker_role": "Founder",
        "phone": "+91-8099195867",
        "contactability": "HIGH",
        "services": ["Shopify Development", "Store Design", "CRO", "Dropshipping"],
        "certifications": ["Shopify Partner"],
        "tier": "B",
        "client_access_score": 75,
        "comai_fit_score": 70,
        "final_score": 72,
        "why_this_agency": "1500+ stores built. $75M+ client revenue. 7+ years Shopify. Dedicated in-house team.",
        "comai_fit": "Every Shopify store is a potential COMAI installation.",
        "pitch_angle": "Ecomking built 1500+ Shopify stores. COMAI installs on all of them.",
        "source": "manual_research",
    },
    {
        "agency_name": "FutureTecheiz",
        "agency_url": "https://futuretechiez.in",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "10-20",
        "clients": "50+ brands scaled to ₹1Cr+ monthly revenue",
        "client_count": 50,
        "decision_maker": "Ashif Iqbal",
        "decision_maker_role": "Founder & Growth Strategist",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Shopify Development", "CRO", "Email Marketing"],
        "certifications": ["Meta Business Partner", "Shopify Partner", "Google Partner"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "final_score": 70,
        "why_this_agency": "50+ brands to ₹1Cr+ monthly. 4.9 rated on Shopify Experts. 250+ store builds.",
        "comai_fit": "Shopify D2C brands need WhatsApp commerce.",
        "pitch_angle": "FutureTecheiz scales 50+ Shopify brands. COMAI installs on their stores.",
        "source": "manual_research",
    },
    {
        "agency_name": "AdYogi",
        "agency_url": "https://adyogi.com",
        "country": "India",
        "city": "Gurugram",
        "agency_type": "eCommerce Performance Marketing Platform",
        "employees": "150-200",
        "founded": 2014,
        "clients": "200+ DTC & Retail brands including Tata Westside, Shoppers Stop, Manyavar, Levi's, Forest Essentials",
        "client_count": 200,
        "revenue_managed": "$100M+ annual ad spend",
        "decision_maker": "Anshuk Aggarwal",
        "decision_maker_role": "Co-Founder",
        "linkedin": "https://linkedin.com/in/anshukaggarwal",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Amazon Ads", "Full-Funnel Performance", "Product Performance Management"],
        "certifications": ["Meta APAC Top 10 Partner", "Google Top eCommerce Partner"],
        "tier": "A",
        "client_access_score": 85,
        "comai_fit_score": 70,
        "final_score": 78,
        "why_this_agency": "200+ brands. $100M+ annual ad spend. Meta Top 10 APAC. Tata, Shoppers Stop, Levi's, Forest Essentials.",
        "comai_fit": "Enterprise D2C/retail brands need WhatsApp commerce at scale.",
        "pitch_angle": "AdYogi manages $100M+ for 200+ brands. COMAI adds WhatsApp commerce to their enterprise clients.",
        "source": "manual_research",
    },
    {
        "agency_name": "Nilesh Soni Consulting",
        "agency_url": "https://nileshsoni.in",
        "country": "India",
        "city": "Delhi NCR",
        "agency_type": "D2C Growth Consultant",
        "employees": "1-10",
        "clients": "D2C brands (800-1000 orders/day Shopify stores)",
        "decision_maker": "Nilesh Soni",
        "decision_maker_role": "Founder",
        "email": "nilesh.soni@iiml.org",
        "phone": "+91-9584006779",
        "linkedin": "https://linkedin.com/in/nileshsoni",
        "contactability": "HIGH",
        "services": ["Shopify Development", "Growth Strategy", "Marketing Automation", "Shopify SEO", "Go-to-Market Strategy"],
        "tier": "C",
        "client_access_score": 55,
        "comai_fit_score": 75,
        "final_score": 65,
        "why_this_agency": "IIM Lucknow. Ex-Nykaa Fashion, Ex-Paytm Mall, Ex-Kult. 50+ engineers team.",
        "comai_fit": "Shopify D2C brands need WhatsApp commerce. Ex-Nykaa background.",
        "pitch_angle": "Nilesh (Ex-Nykaa) helps D2C brands. COMAI adds WhatsApp commerce.",
        "source": "manual_research",
    },
]

async def main():
    conn = await asyncpg.connect(host='127.0.0.1', port=5432, database='beacon', user='beacon', password='beacon_password')
    inserted = 0
    for lead in LEADS:
        lead['id'] = str(uuid.uuid4())
        lead['status'] = 'NEW'
        lead['outreach_sent'] = False
        lead['response_received'] = False
        lead['meeting_scheduled'] = False
        lead['partner_converted'] = False
        for key in ['notable_clients', 'notable_results', 'decision_makers', 'services', 'certifications', 'tags']:
            lead[key] = json.dumps(lead.get(key) or [])
        lead['evidence'] = json.dumps({})
        try:
            await conn.execute(
                '''INSERT INTO partner_leads (id, agency_name, agency_url, country, city, agency_type, employees, founded, clients, client_count, revenue_generated, revenue_managed, notable_clients, notable_results, decision_maker, decision_maker_role, decision_makers, email, phone, linkedin, contactability, services, certifications, tier, client_access_score, comai_fit_score, partner_intent, final_score, why_this_agency, comai_fit, pitch_angle, source, status, outreach_sent, response_received, meeting_scheduled, partner_converted, evidence, tags) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15,$16,$17::jsonb,$18,$19,$20,$21,$22::jsonb,$23::jsonb,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38::jsonb,$39::jsonb)''',
                lead['id'], lead['agency_name'], lead.get('agency_url'), lead.get('country'),
                lead.get('city'), lead.get('agency_type'), lead.get('employees'), lead.get('founded'),
                lead.get('clients'), lead.get('client_count'), lead.get('revenue_generated'),
                lead.get('revenue_managed'), lead['notable_clients'], lead['notable_results'],
                lead.get('decision_maker'), lead.get('decision_maker_role'), lead['decision_makers'],
                lead.get('email'), lead.get('phone'), lead.get('linkedin'), lead.get('contactability'),
                lead['services'], lead['certifications'], lead.get('tier'),
                lead.get('client_access_score'), lead.get('comai_fit_score'),
                lead.get('partner_intent'), lead.get('final_score'),
                lead.get('why_this_agency'), lead.get('comai_fit'), lead.get('pitch_angle'),
                lead.get('source'), lead['status'], lead['outreach_sent'],
                lead['response_received'], lead['meeting_scheduled'],
                lead['partner_converted'], lead['evidence'], lead['tags']
            )
            inserted += 1
            phone = lead.get('phone', '')
            print(f'  INSERTED: {lead["agency_name"]} (Tier {lead.get("tier", "C")}) Phone: {phone}')
        except Exception as e:
            print(f'  ERROR: {lead["agency_name"]} - {e}')
    await conn.close()
    print(f'\n  Total inserted: {inserted}/{len(LEADS)}')

asyncio.run(main())
