"""Insert batch 3 of mega leads for COMAI B2B with real phone numbers"""
import asyncio
import asyncpg

DB_DSN = "postgresql://beacon:beacon_password@127.0.0.1:5432/beacon"

LEADS = [
    # Cognito IT Consultancy - Shopify D2C Agency, Bangalore
    {
        "agency_name": "Cognito IT Consultancy",
        "agency_url": "https://cognitoitconsultancy.com",
        "city": "Bangalore",
        "country": "India",
        "agency_type": "Shopify D2C Agency",
        "employees": "10-20",
        "description": "Verified Shopify Partner, Shopify-only D2C agency. 10+ years experience. 100+ stores across India, USA, UK, UAE & Australia. Fixed price, 2-3 weeks delivery.",
        "decision_maker": "Sanjay Kumar",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "+918147717676",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Established Shopify-only partner, 10+ years, 100+ stores. Deep India D2C expertise.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 85,
    },
    # Friction Studio - Shopify Agency, Jaipur
    {
        "agency_name": "Friction Studio",
        "agency_url": "https://friction.studio",
        "city": "Jaipur",
        "country": "India",
        "agency_type": "Shopify Design & Development Agency",
        "employees": "1-5",
        "description": "Shopify design and development agency. Helps D2C brands sell more online. Founded 2020, Jaipur.",
        "decision_maker": "Vishal Goswami",
        "decision_maker_role": "Founder & CEO",
        "email": "vishal@friction.studio",
        "phone": "+916378376173",
        "linkedin": "https://linkedin.com/company/friction-studio",
        "tier": "B",
        "why_this_agency": "Shopify specialist, design-focused, D2C brands.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # Dev Launch Lab - Shopify Partners, Surat
    {
        "agency_name": "Dev Launch Lab",
        "agency_url": "https://devlaunchlab.com",
        "city": "Surat",
        "country": "India",
        "agency_type": "Shopify Development Agency",
        "employees": "5-10",
        "description": "Shopify Partner since 2023. Top-rated Shopify experts, 4+ years experience. Store setup and migration.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "info@devlaunchlab.com",
        "phone": "+919726184312",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Shopify Partner, store setup specialists.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # Codezania - Shopify Development, Delhi
    {
        "agency_name": "Codezania",
        "agency_url": "https://www.codezania.in",
        "city": "West Delhi",
        "country": "India",
        "agency_type": "Shopify Development Agency",
        "employees": "1-5",
        "description": "Shopify store transformation into growth engines. Custom app development, advanced integrations, AI-driven automation.",
        "decision_maker": "Arun Arora",
        "decision_maker_role": "Co-Founder",
        "email": "",
        "phone": "+918860276039",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Shopify dev, custom apps, AI automation.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # DOREC - Shopify Agency
    {
        "agency_name": "DOREC",
        "agency_url": "https://dorec.in",
        "city": "India",
        "country": "India",
        "agency_type": "Shopify Development Agency",
        "employees": "5-10",
        "description": "Digital solutions agency specializing in Shopify development, conversion optimization, and full-scale e-commerce performance management.",
        "decision_maker": "Sahil Gupta",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "+917827718504",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Shopify development, conversion optimization.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # The Night Marketer - Digital Agency, Delhi
    {
        "agency_name": "The Night Marketer",
        "agency_url": "https://thenightmarketer.com",
        "city": "New Delhi",
        "country": "India",
        "agency_type": "Digital Agency",
        "employees": "10-20",
        "description": "Shopify Select Partner since 2018. 450+ businesses served. Shopify development, UI/UX, CRO, SEO, performance marketing, automation.",
        "decision_maker": "Raghav Mittal",
        "decision_maker_role": "Founder",
        "email": "info@thenightmarketer.com",
        "phone": "+919717884659",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Shopify Select Partner, 450+ businesses, full-service digital agency.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 85,
    },
    # FutureTecheiz - D2C Growth Agency
    {
        "agency_name": "FutureTecheiz",
        "agency_url": "https://futuretechiez.in",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "5-10",
        "description": "Premium growth partner for D2C & Shopify brands. 4.9★ on Shopify Experts, 50+ brands scaled to ₹1Cr+ monthly. Meta Business Partner, Shopify Partner, Google Partner.",
        "decision_maker": "Ashif Iqbal",
        "decision_maker_role": "Founder & Growth Strategist",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Shopify Partner + Meta + Google, 50+ brands scaled, strong D2C track record.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 28,
        "final_score": 70,
    },
    # 100Days - D2C Commerce Agency
    {
        "agency_name": "100Days",
        "agency_url": "https://go100days.com",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Commerce Agency",
        "employees": "10-20",
        "description": "Shopify & Ecommerce Experts. Founded by Bombay Shaving Company founders. D2C store builds, CRO, CRM & WhatsApp, Quick Commerce.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "hello@go100days.com",
        "phone": "+919211446106",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Founded by BSC founders, full commerce stack, WhatsApp commerce.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 85,
    },
    # Scalecraft - Shopify Growth Studio, Delhi
    {
        "agency_name": "Scalecraft",
        "agency_url": "https://thescalecraft.com",
        "city": "Delhi",
        "country": "India",
        "agency_type": "Shopify Growth Studio",
        "employees": "5-10",
        "description": "Senior Shopify growth for Indian D2C brands. CRO, Shopify development, paid ads. One team, one funnel. 5+ years Indian D2C.",
        "decision_maker": "",
        "decision_maker_role": "",
        "email": "",
        "phone": "+918595693910",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Shopify growth studio, full-funnel D2C.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # Nilesh Soni - D2C Growth Partner, Delhi
    {
        "agency_name": "Nilesh Soni Consulting",
        "agency_url": "https://nileshsoni.in",
        "city": "Delhi NCR",
        "country": "India",
        "agency_type": "D2C Growth Consultancy",
        "employees": "1-5",
        "description": "One-stop growth partner for D2C founders & VCs. Shopify builds, SEO, marketing automation. 50+ engineer team. Ex-Nykaa Fashion, Ex-Paytm Mall.",
        "decision_maker": "Nilesh Soni",
        "decision_maker_role": "Founder",
        "email": "nilesh.soni@iiml.org",
        "phone": "+919584006779",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "IIM alumni, ex-Nykaa/Paytm, Shopify builds, D2C expertise.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # Akhil Khanna - eCommerce Specialist, Delhi
    {
        "agency_name": "Akhil Khanna Digital",
        "agency_url": "https://akhilkhanna.com",
        "city": "Delhi",
        "country": "India",
        "agency_type": "eCommerce Specialist",
        "employees": "1-5",
        "description": "Shopify & WooCommerce store builder. Meta & Instagram ad campaigns. 9+ years experience, ₹40Cr+ online revenue generated.",
        "decision_maker": "Akhil Khanna",
        "decision_maker_role": "Founder",
        "email": "hello@akhilkhanna.com",
        "phone": "+919650071995",
        "linkedin": "",
        "tier": "B",
        "why_this_agency": "Shopify/WooCommerce specialist, strong ad expertise.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
    # CodeTasker - Shopify Agency, Surat
    {
        "agency_name": "CodeTasker",
        "agency_url": "https://codetasker.com",
        "city": "Surat",
        "country": "India",
        "agency_type": "Shopify Development Agency",
        "employees": "1-5",
        "description": "Select Shopify Partner. 1000+ Shopify projects over 9 years. Brands: Mokobara, Juicy Chemistry, Vilvah, Kushal's.",
        "decision_maker": "Bhagawati Lal Suthar",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "https://linkedin.com/in/bhagawatilalsuthar",
        "tier": "A",
        "why_this_agency": "Shopify Partner, 1000+ projects, top brand clients.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 28,
        "final_score": 70,
    },
    # Yuvichaar Funnels - AI-Enabled Growth Partners
    {
        "agency_name": "Yuvichaar Funnels",
        "agency_url": "https://www.yuvichaarfunnels.com",
        "city": "India",
        "country": "India",
        "agency_type": "D2C Growth Agency",
        "employees": "10-20",
        "description": "AI-Enabled Growth Partners for D2C Founders. 75+ D2C brands, ₹60Cr+ ad spend managed. Meta & Google certified. PhysicsWallah partnership.",
        "decision_maker": "Yuvraj Singh Rajawat",
        "decision_maker_role": "Founder & Managing Partner",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "Large scale D2C growth, AI-enabled, ₹150Cr+ revenue generated.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 70,
    },
    # FlashReach - Performance Marketing for D2C
    {
        "agency_name": "FlashReach",
        "agency_url": "https://flashreach.io",
        "city": "India",
        "country": "India",
        "agency_type": "Performance Marketing Agency",
        "employees": "10-20",
        "description": "Performance marketing for ambitious D2C brands. 100+ brands, ₹100Cr+ profitable revenue generated. Meta & Google Ads, CRO, retention.",
        "decision_maker": "Navneet",
        "decision_maker_role": "Co-Founder",
        "email": "",
        "phone": "",
        "linkedin": "",
        "tier": "A",
        "why_this_agency": "100+ D2C brands, enterprise-grade performance thinking.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 24,
        "final_score": 70,
    },
    # Digital Saichandu - AI-Powered Digital Marketing, Hyderabad
    {
        "agency_name": "Digital Saichandu",
        "agency_url": "",
        "city": "Hyderabad",
        "country": "India",
        "agency_type": "AI-Powered Digital Marketing Agency",
        "employees": "1-5",
        "description": "India's first fully AI-powered digital marketing agency. WhatsApp Business API, n8n automation, Meta Ads, Google Ads. 50+ clients.",
        "decision_maker": "Saichandu Goud",
        "decision_maker_role": "Founder",
        "email": "rockychandu91@gmail.com",
        "phone": "+919700162442",
        "linkedin": "https://linkedin.com/in/saichandugoud",
        "tier": "B",
        "why_this_agency": "AI-powered agency, WhatsApp API, automation.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # Digitrixpro - Shopify eCommerce Marketing, Chennai
    {
        "agency_name": "Digitrixpro",
        "agency_url": "",
        "city": "Chennai",
        "country": "India",
        "agency_type": "Shopify eCommerce Marketing Agency",
        "employees": "1-5",
        "description": "Helping Shopify ecommerce stores add $800k-$1M per year through performance marketing and WhatsApp conversational commerce.",
        "decision_maker": "Dinesh Babu",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "+919940581342",
        "linkedin": "https://linkedin.com/in/dinesh-babu-e",
        "tier": "B",
        "why_this_agency": "Shopify + WhatsApp conversational commerce specialist.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 28,
        "final_score": 72,
    },
    # DNA Digital - AI Marketing & Automation Agency
    {
        "agency_name": "DNA Digital",
        "agency_url": "",
        "city": "New Delhi",
        "country": "India",
        "agency_type": "AI Marketing & Automation Agency",
        "employees": "1-5",
        "description": "AI-powered marketing and automation agency. DIGIMONK.AI WhatsApp automation, Meta & Google Ads, Amazon Growth, 16+ years experience.",
        "decision_maker": "DJ",
        "decision_maker_role": "Founder & CEO",
        "email": "",
        "phone": "+919873362362",
        "linkedin": "https://linkedin.com/in/djdigitalmarketingexpert",
        "tier": "B",
        "why_this_agency": "AI WhatsApp automation, performance marketing.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # Hype & Reach - Performance Marketing & WhatsApp Automation, Noida
    {
        "agency_name": "Hype & Reach",
        "agency_url": "",
        "city": "Noida",
        "country": "India",
        "agency_type": "Performance Marketing & WhatsApp Automation",
        "employees": "5-10",
        "description": "Growth engines, not just campaigns. Performance marketing, WhatsApp automation (Flint API), AI-powered systems. 400K+ leads generated.",
        "decision_maker": "Dr. Kunal Gupta",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "https://linkedin.com/in/dr-kunal-gupta-9b6ba61a5",
        "tier": "B",
        "why_this_agency": "WhatsApp API (Flint API), performance marketing, AI automation.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 28,
        "final_score": 65,
    },
    # Vimal Bachani - D2C Performance & Retention, Ahmedabad
    {
        "agency_name": "Vimal Bachani Consulting",
        "agency_url": "",
        "city": "Ahmedabad",
        "country": "India",
        "agency_type": "D2C Performance & Retention",
        "employees": "1-5",
        "description": "Performance & retention marketing for D2C. Meta & Google Ads, WhatsApp retention, 100M+ revenue generated. 8+ years experience.",
        "decision_maker": "Vimal Bachani",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "+917984795814",
        "linkedin": "https://linkedin.com/in/vimal-bachani",
        "tier": "B",
        "why_this_agency": "D2C performance + WhatsApp retention specialist.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 24,
        "final_score": 72,
    },
    # AdCruize Agency - Digital Marketing, Bangalore
    {
        "agency_name": "AdCruize Agency",
        "agency_url": "",
        "city": "Bangalore",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "1-5",
        "description": "Performance marketing, Meta Ads, SEO, Email & WhatsApp Marketing. E-commerce growth. Amazon, Flipkart & Myntra marketplace expert.",
        "decision_maker": "Ritesh Mishra",
        "decision_maker_role": "Founder",
        "email": "",
        "phone": "",
        "linkedin": "https://linkedin.com/in/ritesh-mishra2000",
        "tier": "C",
        "why_this_agency": "Multi-marketplace + WhatsApp marketing.",
        "contactability": "new",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 15,
        "comai_fit_score": 20,
        "final_score": 45,
    },
    # Eprofess Group - Digital Marketing Agency, Mohali
    {
        "agency_name": "Eprofess Group",
        "agency_url": "",
        "city": "Mohali",
        "country": "India",
        "agency_type": "Digital Marketing Agency",
        "employees": "10-20",
        "description": "Digital marketing agency. SEO, PPC, social media marketing, branding. Founded 2013, 13+ years. Meta Ads & Google Ads.",
        "decision_maker": "Bharat Bansal",
        "decision_maker_role": "Founder",
        "email": "info@eprofess.in",
        "phone": "+918699538538",
        "linkedin": "https://linkedin.com/in/bharatbbansal",
        "tier": "B",
        "why_this_agency": "Established agency, 13+ years, Meta & Google Ads.",
        "contactability": "phone_verified",
        "status": "NEW",
        "lead_source": "comai_b2b",
        "client_access_score": 35,
        "comai_fit_score": 20,
        "final_score": 72,
    },
]

async def insert():
    conn = await asyncpg.connect(DB_DSN)
    try:
        inserted = 0
        skipped = 0
        for lead in LEADS:
            # Check if already exists
            exists = await conn.fetchval(
                "SELECT id FROM partner_leads WHERE agency_name = $1",
                lead["agency_name"]
            )
            if exists:
                skipped += 1
                continue
            await conn.execute(
                """INSERT INTO partner_leads 
                   (agency_name, agency_url, city, country, agency_type, employees,
                    description, decision_maker, decision_maker_role, email, phone, linkedin,
                    tier, why_this_agency, contactability, status, lead_source,
                    client_access_score, comai_fit_score, final_score)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)""",
                lead["agency_name"], lead["agency_url"], lead["city"],
                lead["country"], lead["agency_type"], lead["employees"],
                lead["description"], lead["decision_maker"], lead["decision_maker_role"],
                lead["email"], lead["phone"], lead["linkedin"],
                lead["tier"], lead["why_this_agency"], lead["contactability"],
                lead["status"], lead["lead_source"],
                lead["client_access_score"], lead["comai_fit_score"], lead["final_score"],
            )
            inserted += 1
            print(f"  INSERTED: {lead['agency_name']} | {lead['phone'] or 'no phone'} | {lead['email'] or 'no email'}")
        
        total = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b'")
        with_phone = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND phone != '' AND phone IS NOT NULL")
        with_email = await conn.fetchval("SELECT COUNT(*) FROM partner_leads WHERE lead_source = 'comai_b2b' AND email != '' AND email IS NOT NULL")
        
        print(f"\nRESULTS: {inserted} inserted, {skipped} skipped (duplicates)")
        print(f"TOTAL comai_b2b: {total} leads | {with_phone} with phone | {with_email} with email")
    finally:
        await conn.close()

asyncio.run(insert())
