"""Insert all COMAI B2B partner leads into PostgreSQL."""
import json
import uuid
import asyncpg
import asyncio

LEADS = [
    # TIER A
    {
        "agency_name": "Socio Labs",
        "agency_url": "https://sociolabs.in",
        "country": "India",
        "city": "New Delhi",
        "agency_type": "D2C Marketing Agency",
        "employees": "58",
        "founded": 2016,
        "clients": "1800+ brands across 20+ categories",
        "client_count": 1800,
        "revenue_managed": "₹200Cr+ ad spend, ₹2500Cr+ revenue generated",
        "notable_clients": [],
        "decision_maker": "Nayan Mittal",
        "decision_maker_role": "CEO & Founder",
        "decision_makers": [],
        "email": "nayan@sociolabs.in",
        "phone": "+91-9650750546",
        "linkedin": "https://linkedin.com/in/nayan-mittal-digital-marketing-expert",
        "contactability": "HIGH",
        "services": ["performance marketing", "SEO", "PPC", "Google Ads", "Meta Ads", "Shopify", "email marketing", "WhatsApp"],
        "certifications": ["Google Premier Partner", "Meta Business Partner", "Shopify Partner"],
        "tier": "A",
        "client_access_score": 85,
        "comai_fit_score": 85,
        "partner_intent": "UNKNOWN",
        "final_score": 85,
        "why_this_agency": "Largest agency. 1800+ D2C brands. Google Premier Partner. Shopify Partner. Already offers WhatsApp automation.",
        "comai_fit": "Clients sell D2C products — exactly who needs WhatsApp commerce. Can bundle COMAI with marketing services.",
        "pitch_angle": "Socio Labs manages ₹200Cr+ in ad spend for 1800+ D2C brands. COMAI can be offered as retention/conversion layer to every client.",
        "source": "manual_research",
    },
    {
        "agency_name": "D2CWolf",
        "agency_url": "https://d2cwolf.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "1-10",
        "founded": 2019,
        "clients": "350+ brands scaled, 107+ beyond ₹1 Cr/month",
        "client_count": 350,
        "revenue_generated": "₹417Cr+ attributed client revenue",
        "revenue_managed": "₹250Cr+ ad spend managed",
        "notable_clients": ["Tata CLiQ"],
        "decision_maker": "Hrishik Shetty",
        "decision_maker_role": "Founder",
        "email": "hrish@d2cwolf.com",
        "linkedin": "https://linkedin.com/in/hrishikshetty",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Performance Marketing", "UGC", "Creative Strategy"],
        "tier": "A",
        "client_access_score": 80,
        "comai_fit_score": 75,
        "partner_intent": "UNKNOWN",
        "final_score": 80,
        "why_this_agency": "Ex-Tata CLiQ performance marketer. Revenue-linked fee model. Works with 30 D2C founders per quarter.",
        "comai_fit": "Clients doing ₹4L-₹30L/month — Sweet Spot for WhatsApp commerce.",
        "pitch_angle": "D2CWolf has scaled 350+ D2C brands. WhatsApp commerce is the next revenue channel.",
        "source": "manual_research",
    },
    {
        "agency_name": "TruImpact",
        "agency_url": "https://truimpact.io",
        "country": "India",
        "city": "Pune",
        "agency_type": "D2C Growth Agency",
        "employees": "1-10",
        "founded": 2024,
        "clients": "210+ D2C brands",
        "client_count": 210,
        "revenue_generated": "₹850Cr+ generated for 210+ D2C brands",
        "notable_clients": ["Sirona", "Peesafe", "Setu", "PlanB", "Curious Cub", "Bazoo"],
        "decision_maker": "Suril Shah",
        "decision_maker_role": "Co-Founder",
        "decision_makers": ["Abdulqadir Dahodwala (Co-Founder)"],
        "email": "hi@truimpact.io",
        "phone": "+91-9106399347",
        "linkedin": "https://linkedin.com/in/srtsuril",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "CRO", "Performance Marketing"],
        "tier": "A",
        "client_access_score": 75,
        "comai_fit_score": 80,
        "partner_intent": "UNKNOWN",
        "final_score": 78,
        "why_this_agency": "Two founders, no layers. AB manages $200K+/month ad spend. Tied to P&L outcomes.",
        "comai_fit": "Clients (Sirona, Peesafe, Setu) are exactly the D2C brands that need WhatsApp commerce.",
        "pitch_angle": "TruImpact generates ₹850Cr+ for 210+ D2C brands. WhatsApp commerce is the next channel.",
        "source": "manual_research",
    },
    {
        "agency_name": "Aim n Launch",
        "agency_url": "https://aimnlaunch.com",
        "country": "India",
        "city": "New Delhi",
        "agency_type": "eCommerce Marketing Agency",
        "employees": "2",
        "founded": 2020,
        "clients": "50+ D2C brands, 100+ businesses total",
        "client_count": 100,
        "revenue_generated": "₹57Cr+ in client revenue",
        "notable_clients": ["Shark Tank India brands"],
        "decision_maker": "Vivek Kumar",
        "decision_maker_role": "Founder",
        "email": "vivek@aimnlaunch.com",
        "phone": "+91-9971153771",
        "linkedin": "https://linkedin.com/in/vivek-kumar-strategy",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "SEO", "Shopify", "WhatsApp Marketing", "Email Marketing"],
        "tier": "A",
        "client_access_score": 70,
        "comai_fit_score": 80,
        "partner_intent": "UNKNOWN",
        "final_score": 75,
        "why_this_agency": "Scaled Shark Tank India brands. Already offers WhatsApp marketing. Full-funnel approach.",
        "comai_fit": "They already do WhatsApp marketing manually — COMAI automates and scales it.",
        "pitch_angle": "Aim n Launch already offers WhatsApp marketing to 50+ D2C brands. COMAI automates WhatsApp commerce.",
        "source": "manual_research",
    },
    {
        "agency_name": "HavStrategy",
        "agency_url": "https://www.havstrategy.com",
        "country": "India",
        "city": "Delhi NCR",
        "agency_type": "D2C Ecommerce Marketing Agency",
        "employees": "1-10",
        "founded": 2020,
        "clients": "150+ D2C brands",
        "client_count": 150,
        "revenue_generated": "$15M+ ecommerce revenue",
        "revenue_managed": "5Mn+ leads",
        "notable_clients": ["Diam Beauty", "Fae Beauty", "Simply Nam"],
        "decision_maker": "Sakshi Makkar",
        "decision_maker_role": "Founder & Creative Head",
        "phone": "+91-8750998314",
        "linkedin": "https://linkedin.com/in/makkar-sakshi",
        "contactability": "MEDIUM",
        "services": ["Performance Marketing", "Google Ads", "Meta Ads", "SEO", "Influencer Marketing"],
        "certifications": ["Google Premier Partner", "Meta Business Partner"],
        "tier": "A",
        "client_access_score": 70,
        "comai_fit_score": 80,
        "partner_intent": "UNKNOWN",
        "final_score": 75,
        "why_this_agency": "Specialist for beauty, fashion, lifestyle. 150+ brands. Meta + Google certified.",
        "comai_fit": "Beauty/fashion/lifestyle brands are perfect WhatsApp commerce users (high AOV, repeat purchases).",
        "pitch_angle": "HavStrategy has scaled 150+ D2C beauty/fashion brands. WhatsApp commerce converts 3-5x better than email.",
        "source": "manual_research",
    },
    {
        "agency_name": "Neuroid",
        "agency_url": "https://www.neuroidmedia.com",
        "country": "India",
        "city": "New Delhi",
        "agency_type": "Integrated Growth & Creative Studio",
        "employees": "10-20",
        "founded": 2019,
        "clients": "100+ D2C brands",
        "client_count": 100,
        "revenue_generated": "₹400Cr+ attributed client revenue",
        "notable_clients": ["Wooden Street", "Kisah", "Jewelsmars", "Lifelong", "Sylvi"],
        "decision_maker": "Laksh Sehgal",
        "decision_maker_role": "Founder",
        "email": "hello@neuroidmedia.com",
        "linkedin": "https://linkedin.com/in/lakshsehgal",
        "contactability": "MEDIUM",
        "services": ["Performance Marketing", "Meta Ads", "Google Ads", "UGC", "CRO", "Retention"],
        "tier": "A",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "partner_intent": "UNKNOWN",
        "final_score": 73,
        "why_this_agency": "Full-loop agency — performance marketing + creative + retention. 50+ creatives/month.",
        "comai_fit": "Retention/CRO focus means they already think about post-acquisition revenue.",
        "pitch_angle": "Neuroid runs the whole loop. WhatsApp commerce is the missing retention channel.",
        "source": "manual_research",
    },
    # TIER B
    {
        "agency_name": "Sorted Agency",
        "agency_url": "https://sorted.agency",
        "country": "India",
        "city": "Pune",
        "agency_type": "eCommerce Growth Agency",
        "employees": "10-20",
        "clients": "100+ D2C brands, 5+ Shark Tank USA brands",
        "client_count": 100,
        "revenue_managed": "$425M Shopify revenue 2025, $30M+ ad spend managed",
        "email": "hello@sorted.agency",
        "linkedin": "https://linkedin.com/company/sorted-agency",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Klaviyo", "Shopify CRO", "AI Automation", "White-label"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 80,
        "partner_intent": "UNKNOWN",
        "final_score": 75,
        "why_this_agency": "AI-first agency. Klaviyo+Meta+Shopify. White-label for agencies. $425M revenue managed.",
        "comai_fit": "AI-first approach matches COMAI. White-label capability means they can resell COMAI.",
        "pitch_angle": "Sorted Agency manages $425M Shopify revenue. COMAI plugs into Shopify as WhatsApp commerce layer.",
        "source": "manual_research",
    },
    {
        "agency_name": "Digidonut",
        "agency_url": "https://digidonut.com",
        "country": "India",
        "city": "Gurugram",
        "agency_type": "Full-Funnel Growth Agency",
        "employees": "11",
        "clients": "50+ brands across 6 industries",
        "client_count": 50,
        "decision_maker": "Pragya Upadhyay",
        "decision_maker_role": "Co-Founder",
        "decision_makers": ["Harsha Tiwari (Co-Founder)"],
        "linkedin": "https://linkedin.com/company/digidonut",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Marketplace", "SEO", "Email", "WhatsApp", "Influencer"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "partner_intent": "UNKNOWN",
        "final_score": 70,
        "why_this_agency": "Data-driven D2C agency. Team from Merkle Sokrati. Amazon Advertising Award.",
        "comai_fit": "50+ brands across fashion, beauty, home — perfect COMAI users.",
        "pitch_angle": "Digidonut data-driven approach + COMAI analytics = powerful combination.",
        "source": "manual_research",
    },
    {
        "agency_name": "Forty",
        "agency_url": "https://www.createwithforty.com",
        "country": "India",
        "agency_type": "Creative + Performance Studio",
        "employees": "1-10",
        "founded": 2024,
        "decision_maker": "Yash Gupta",
        "decision_maker_role": "Co-Founder",
        "decision_makers": ["Satwik Vaishnava (Co-Founder, Ex-Google India)"],
        "linkedin": "https://linkedin.com/in/satwikvaishnava",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Content", "Brand", "CRO", "SEO", "Shopify"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "partner_intent": "UNKNOWN",
        "final_score": 70,
        "why_this_agency": "Ex-Google founders. 400% ROAS, 390% MoM sales growth. Data + creativity accountability.",
        "comai_fit": "Ecommerce brands need WhatsApp commerce. Data-driven approach matches COMAI.",
        "pitch_angle": "Forty makes creative accountable. COMAI ties directly to revenue.",
        "source": "manual_research",
    },
    {
        "agency_name": "ITD GrowthLabs",
        "agency_url": "https://itdgrowthlabs.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Marketing Agency",
        "employees": "1-10",
        "clients": "300+ clients",
        "client_count": 300,
        "decision_maker": "Prashant Chaudhari",
        "decision_maker_role": "Business Head",
        "decision_makers": ["Loy Thomas (Technology Solutions)"],
        "email": "info@itdgrowthlabs.com",
        "phone": "+91-8450978544",
        "contactability": "MEDIUM",
        "services": ["Digital Marketing", "Social Media", "SEO", "PPC", "Google Ads", "Meta Ads"],
        "tier": "B",
        "client_access_score": 75,
        "comai_fit_score": 70,
        "partner_intent": "UNKNOWN",
        "final_score": 73,
        "why_this_agency": "300+ clients — highest client count. Beauty, D2C, retail focus.",
        "comai_fit": "Beauty/D2C/retail clients need WhatsApp commerce. 300+ clients = massive distribution.",
        "pitch_angle": "ITD GrowthLabs serves 300+ beauty/D2C/retail clients. WhatsApp commerce is the next channel.",
        "source": "manual_research",
    },
    {
        "agency_name": "Ixoric Technologies",
        "agency_url": "https://ixoric.com",
        "country": "India",
        "city": "Bengaluru",
        "agency_type": "Digital Marketing Agency",
        "employees": "1-10",
        "founded": 2013,
        "clients": "200+ clients",
        "client_count": 200,
        "decision_maker": "Prashant Kumar",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/prashantkumar",
        "contactability": "MEDIUM",
        "services": ["AI SEO", "Google Shopping", "Meta Ads", "Email Retention", "CRO"],
        "certifications": ["Google Certified"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 70,
        "partner_intent": "UNKNOWN",
        "final_score": 70,
        "why_this_agency": "11+ years in ecommerce. IIT-trained founder. 200+ clients. Deep attribution expertise.",
        "comai_fit": "Ecommerce clients need WhatsApp commerce. Attribution expertise values COMAI analytics.",
        "pitch_angle": "Ixoric fixes broken attribution. COMAI ties directly to revenue attribution.",
        "source": "manual_research",
    },
    {
        "agency_name": "ConvergeX Labs",
        "agency_url": "https://convergexlabs.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Ecommerce Growth Agency",
        "employees": "1-10",
        "founded": 2017,
        "clients": "50+ brands",
        "client_count": 50,
        "revenue_generated": "₹90Cr+",
        "email": "info@convergexdigital.com",
        "phone": "+91-79771-93104",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Shopify", "UGC", "Retention"],
        "certifications": ["Meta Partner", "Shopify Partner"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "partner_intent": "UNKNOWN",
        "final_score": 70,
        "why_this_agency": "Meta + Shopify Partner. 7+ years. Specializes in ₹5-7L → ₹1Cr stage.",
        "comai_fit": "Clients at ₹5-7L/month are Sweet Spot for WhatsApp commerce.",
        "pitch_angle": "ConvergeX helps brands break ₹5-7L plateau. WhatsApp commerce adds 15-25% revenue lift.",
        "source": "manual_research",
    },
    {
        "agency_name": "Tangence",
        "agency_url": "https://www.tangence.in",
        "country": "India",
        "agency_type": "Ecommerce Digital Marketing Agency",
        "employees": "1-10",
        "clients": "D2C brands across fashion, beauty, home",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "SEO", "Email Marketing", "WhatsApp", "CRO"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 70,
        "partner_intent": "UNKNOWN",
        "final_score": 68,
        "why_this_agency": "Already understands email/WhatsApp generate 25-35% of D2C revenue.",
        "comai_fit": "Already selling WhatsApp services — COMAI automates and scales it.",
        "pitch_angle": "Tangence knows WhatsApp generates 25-35% of D2C revenue. COMAI automates WhatsApp commerce.",
        "source": "manual_research",
    },
    {
        "agency_name": "CV Infotech",
        "agency_url": "https://www.cvinfotech.com",
        "country": "India",
        "city": "Gurugram",
        "agency_type": "Shopify Development Agency",
        "employees": "1-10",
        "founded": 2012,
        "clients": "454 projects, 35 reviews at 5.0",
        "client_count": 454,
        "contactability": "MEDIUM",
        "services": ["Shopify", "Shopify Plus", "Custom Development", "Migrations"],
        "certifications": ["Verified Shopify Partner (ID 2454630)"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 65,
        "partner_intent": "UNKNOWN",
        "final_score": 68,
        "why_this_agency": "Verified Shopify Partner since 2012. 454 projects. 14-year client relationships.",
        "comai_fit": "Every Shopify store they build is a potential COMAI installation.",
        "pitch_angle": "CV Infotech builds Shopify stores. COMAI installs in 15 minutes on Shopify.",
        "source": "manual_research",
    },
    {
        "agency_name": "FarziEngineer",
        "agency_url": "https://farziengineer.com",
        "country": "India",
        "city": "Noida/Lucknow",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "1-10",
        "founded": 2013,
        "notable_clients": ["Mamaearth", "boAt", "Wow Skin Science", "PlixLife", "ITC", "Emami", "P&G"],
        "contactability": "LOW",
        "services": ["Shopify Plus", "Custom Themes", "Migrations", "CRO"],
        "certifications": ["Shopify Plus Partner", "ISO 9001", "SOC 2"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 70,
        "partner_intent": "UNKNOWN",
        "final_score": 68,
        "why_this_agency": "Shopify Plus Partner with enterprise clients. 11+ years.",
        "comai_fit": "Enterprise D2C brands need WhatsApp commerce at scale.",
        "pitch_angle": "FarziEngineer builds Shopify Plus stores for Mamaearth, boAt, P&G. COMAI scales with Shopify Plus.",
        "source": "manual_research",
    },
    {
        "agency_name": "The Shizz",
        "agency_url": "https://theshizz.in",
        "country": "India",
        "city": "Bangalore/Kolkata",
        "agency_type": "Performance Marketing Agency",
        "clients": "160+ brands",
        "client_count": 160,
        "revenue_managed": "₹450Cr+ revenue attributed",
        "decision_maker": "Subham",
        "decision_maker_role": "Founder",
        "email": "subham@theshizz.in",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Creative", "Social", "CRO"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 70,
        "partner_intent": "UNKNOWN",
        "final_score": 70,
        "why_this_agency": "160+ brands, all in-house. FMCG/F&B/Nutrition focus. ₹450Cr+ attributed.",
        "comai_fit": "FMCG/F&B brands need WhatsApp commerce for repeat purchases.",
        "pitch_angle": "The Shizz attributes ₹450Cr+ revenue. COMAI adds WhatsApp commerce layer.",
        "source": "manual_research",
    },
    {
        "agency_name": "Founder Cartel",
        "agency_url": "https://foundercartel.com",
        "country": "India",
        "city": "Lucknow",
        "agency_type": "eCommerce Marketing Agency",
        "clients": "50+ DTC brands",
        "client_count": 50,
        "decision_maker": "Divyansh",
        "decision_maker_role": "Founder",
        "email": "foundercartel@gmail.com",
        "phone": "+91-8005319313",
        "linkedin": "https://linkedin.com/company/foundercartel",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Content", "UGC", "WhatsApp", "Email", "Shopify CRO"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 80,
        "partner_intent": "UNKNOWN",
        "final_score": 72,
        "why_this_agency": "Full-funnel D2C. Already does WhatsApp automation. 50+ brands.",
        "comai_fit": "Already does WhatsApp automation — COMAI replaces manual work.",
        "pitch_angle": "Founder Cartel already automates WhatsApp. COMAI scales it with AI chatbot + cart recovery.",
        "source": "manual_research",
    },
    {
        "agency_name": "DigitalDC",
        "agency_url": "https://digitaldc.in",
        "country": "India",
        "city": "Bangalore",
        "agency_type": "Performance Marketing Agency",
        "clients": "200+ D2C & B2B brands",
        "client_count": 200,
        "contactability": "LOW",
        "services": ["Meta Ads", "Google Ads", "CRO", "Attribution", "D2C Strategy"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 65,
        "partner_intent": "UNKNOWN",
        "final_score": 68,
        "why_this_agency": "200+ brands. 16x ROAS capability. Bangalore hub.",
        "comai_fit": "D2C brands need WhatsApp commerce for retention.",
        "pitch_angle": "DigitalDC has 200+ D2C clients. COMAI adds WhatsApp commerce to their stack.",
        "source": "manual_research",
    },
    {
        "agency_name": "OneOrange Digital",
        "agency_url": "https://www.oneorangedigital.com",
        "country": "India",
        "agency_type": "D2C Marketing Agency",
        "clients": "60+ D2C brands",
        "client_count": 60,
        "revenue_managed": "₹88L→₹2.5Cr with 5+ ROAS",
        "decision_maker": "Nitin Kansal",
        "decision_maker_role": "Founder",
        "contactability": "MEDIUM",
        "services": ["Performance Marketing", "Website Development", "Content", "UI/UX", "CRO", "Retention"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 70,
        "partner_intent": "UNKNOWN",
        "final_score": 68,
        "why_this_agency": "60+ D2C brands. Shark Tank clients. Founder-led.",
        "comai_fit": "D2C brands need WhatsApp commerce.",
        "pitch_angle": "OneOrange Digital serves 60+ D2C brands. COMAI adds WhatsApp commerce.",
        "source": "manual_research",
    },
    {
        "agency_name": "Iblix Digital",
        "agency_url": "https://iblixdigital.com",
        "country": "India",
        "city": "Kolkata",
        "agency_type": "Performance Marketing + Shopify Agency",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "UGC", "Shopify", "Custom Themes", "Hydrogen"],
        "tier": "B",
        "client_access_score": 60,
        "comai_fit_score": 70,
        "partner_intent": "UNKNOWN",
        "final_score": 65,
        "why_this_agency": "Only agency bundling Meta + Google + UGC + Shopify under one roof for lifestyle brands.",
        "comai_fit": "Shopify + performance marketing = perfect for COMAI integration.",
        "pitch_angle": "Iblix bundles Shopify + marketing. COMAI installs on Shopify stores they build.",
        "source": "manual_research",
    },
]


async def main():
    conn = await asyncpg.connect(
        host="127.0.0.1",
        port=5432,
        database="beacon",
        user="beacon",
        password="beacon_password",
    )

    inserted = 0
    for lead in LEADS:
        lead["id"] = str(uuid.uuid4())
        lead["status"] = "NEW"
        lead["outreach_sent"] = False
        lead["response_received"] = False
        lead["meeting_scheduled"] = False
        lead["partner_converted"] = False

        # Convert lists to JSON strings
        for key in ["notable_clients", "notable_results", "decision_makers", "services", "certifications", "tags"]:
            if key in lead and lead[key] is not None:
                lead[key] = json.dumps(lead[key])
            else:
                lead[key] = "[]"

        for key in ["evidence"]:
            if key in lead and lead[key] is not None:
                lead[key] = json.dumps(lead[key])
            else:
                lead[key] = "{}"

        try:
            await conn.execute("""
                INSERT INTO partner_leads (
                    id, agency_name, agency_url, country, city, agency_type, employees, founded,
                    clients, client_count, revenue_generated, revenue_managed,
                    notable_clients, notable_results, decision_maker, decision_maker_role,
                    decision_makers, email, phone, linkedin, contactability,
                    services, certifications, tier, client_access_score, comai_fit_score,
                    partner_intent, final_score, why_this_agency, comai_fit, pitch_angle,
                    source, status, outreach_sent, response_received, meeting_scheduled,
                    partner_converted, evidence, tags
                ) VALUES (
                    $1, $2, $3, $4, $5, $6, $7, $8,
                    $9, $10, $11, $12,
                    $13::jsonb, $14::jsonb, $15, $16,
                    $17::jsonb, $18, $19, $20, $21,
                    $22::jsonb, $23::jsonb, $24, $25, $26,
                    $27, $28, $29, $30, $31,
                    $32, $33, $34, $35, $36,
                    $37, $38::jsonb, $39::jsonb
                )
            """,
                lead["id"], lead["agency_name"], lead.get("agency_url"), lead.get("country"),
                lead.get("city"), lead.get("agency_type"), lead.get("employees"), lead.get("founded"),
                lead.get("clients"), lead.get("client_count"), lead.get("revenue_generated"),
                lead.get("revenue_managed"),
                lead["notable_clients"], lead["notable_results"], lead.get("decision_maker"),
                lead.get("decision_maker_role"),
                lead["decision_makers"], lead.get("email"), lead.get("phone"), lead.get("linkedin"),
                lead.get("contactability"),
                lead["services"], lead["certifications"], lead.get("tier"),
                lead.get("client_access_score"), lead.get("comai_fit_score"),
                lead.get("partner_intent"), lead.get("final_score"),
                lead.get("why_this_agency"), lead.get("comai_fit"), lead.get("pitch_angle"),
                lead.get("source"), lead["status"], lead["outreach_sent"],
                lead["response_received"], lead["meeting_scheduled"],
                lead["partner_converted"], lead["evidence"], lead["tags"]
            )
            inserted += 1
            print(f"  INSERTED: {lead['agency_name']} (Tier {lead.get('tier', 'C')})")
        except Exception as e:
            print(f"  ERROR: {lead['agency_name']} — {e}")

    await conn.close()
    print(f"\n  Total inserted: {inserted}/{len(LEADS)}")


if __name__ == "__main__":
    asyncio.run(main())
