"""Insert new batch of 30+ agency leads into PostgreSQL."""
import json
import uuid
import asyncpg
import asyncio

NEW_LEADS = [
    # === SHOPIFY DEVELOPMENT AGENCIES ===
    {
        "agency_name": "FarziEngineer",
        "agency_url": "https://farziengineer.com",
        "country": "India",
        "city": "Noida",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "50-100",
        "clients": "Mamaearth, boAt, Wow Skin Science, PlixLife, ITC, Emami, P&G, Minimalist, Just Herbs, Faces Canada",
        "client_count": 100,
        "contactability": "HIGH",
        "services": ["Shopify Plus Development", "Custom Themes", "Migrations", "CRO", "Integrations", "Headless Commerce"],
        "certifications": ["Shopify Plus Partner", "ISO 9001", "SOC 2"],
        "tier": "A",
        "client_access_score": 85,
        "comai_fit_score": 80,
        "final_score": 82,
        "why_this_agency": "Shopify Plus Partner. 11+ years. Mamaearth, boAt, P&G clients. ISO + SOC2 certified.",
        "comai_fit": "Every Shopify Plus store they build is a potential COMAI installation. Enterprise clients need WhatsApp commerce.",
        "pitch_angle": "FarziEngineer builds Shopify Plus stores for Mamaearth and boAt. COMAI can be bundled as WhatsApp commerce layer for every client.",
        "phone": "9236360145",
        "decision_maker": "FarziEngineer Team",
        "decision_maker_role": "Leadership",
        "source": "manual_research",
    },
    {
        "agency_name": "Aumento Infoway",
        "agency_url": "https://aumentoinfoway.com",
        "country": "India",
        "city": "Ahmedabad",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "20-30",
        "decision_maker": "Pritesh Patel",
        "decision_maker_role": "Founder, CEO & CTO",
        "linkedin": "https://linkedin.com/in/pritesh-shopify-expert",
        "contactability": "HIGH",
        "services": ["Shopify Plus Development", "White Label Shopify", "Headless Commerce", "CRO", "Custom Checkout"],
        "certifications": ["Shopify Plus Partner"],
        "tier": "A",
        "client_access_score": 80,
        "comai_fit_score": 85,
        "final_score": 82,
        "why_this_agency": "Shopify Plus white-label partner for agencies. 10+ years Shopify. 100+ clients. Ahmedabad-based.",
        "comai_fit": "White-label Shopify partner — they build stores for other agencies. COMAI can be white-labeled through them to hundreds of D2C brands.",
        "pitch_angle": "Aumento builds Shopify stores for agencies as white-label partner. COMAI can be white-labeled and distributed through their agency network.",
        "source": "manual_research",
    },
    {
        "agency_name": "Dynamic Dreamz",
        "agency_url": "https://dynamicdreamz.com",
        "country": "India",
        "city": "Surat",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "150-200",
        "decision_maker": "Virag Shah",
        "decision_maker_role": "Founder & CEO",
        "linkedin": "https://linkedin.com/in/virag-shah-950b9b102",
        "contactability": "MEDIUM",
        "services": ["Shopify Plus Development", "Custom Apps", "Migrations", "Headless Commerce", "B2B Shopify"],
        "certifications": ["Shopify Platinum Partner"],
        "tier": "A",
        "client_access_score": 80,
        "comai_fit_score": 75,
        "final_score": 77,
        "why_this_agency": "Shopify Platinum Partner. 150-200 employees. Founded 2004. Global client base across 60+ countries.",
        "comai_fit": "Largest Shopify agency in India. Builds stores for global brands. COMAI can be integrated into every Shopify build.",
        "pitch_angle": "Dynamic Dreamz is India's largest Shopify Plus agency. COMAI adds WhatsApp commerce to their 750+ store portfolio.",
        "source": "manual_research",
    },
    {
        "agency_name": "Ambiw Web Agency",
        "agency_url": "https://ambiw.com",
        "country": "India",
        "city": "Rajkot",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "30-40",
        "decision_maker": "Shahid Sama",
        "decision_maker_role": "Co-Founder & COO",
        "linkedin": "https://linkedin.com/in/shahidsama",
        "contactability": "MEDIUM",
        "services": ["Shopify Plus Development", "Custom eCommerce", "Migrations", "Performance Optimization", "Digital Marketing"],
        "certifications": ["Shopify Plus Partner"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "final_score": 72,
        "why_this_agency": "Shopify Plus Partner since 2012. 30-40 employees. Global clients in India, US, Canada.",
        "comai_fit": "Shopify agency with marketing services. COMAI bundles naturally with their client offerings.",
        "pitch_angle": "Ambiw builds Shopify stores globally. COMAI adds WhatsApp commerce to their client base.",
        "source": "manual_research",
    },
    {
        "agency_name": "Avid Brio",
        "agency_url": "https://avidbrio.com",
        "country": "India",
        "city": "Ahmedabad",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "30-40",
        "decision_maker": "Hitesh Matlani",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/hiteshmatlani",
        "contactability": "MEDIUM",
        "services": ["Shopify Plus Development", "Custom Builds", "Luxury eCommerce", "AI in Retail", "Headless Commerce"],
        "certifications": ["Shopify Premier Partner"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "final_score": 72,
        "why_this_agency": "Shopify Premier Partner. 30-40 employees. Luxury eCommerce focus. AI in retail.",
        "comai_fit": "Luxury D2C brands need WhatsApp commerce for high-AOV products.",
        "pitch_angle": "Avid Brio builds luxury Shopify stores. COMAI adds WhatsApp commerce for premium D2C brands.",
        "source": "manual_research",
    },
    {
        "agency_name": "Codingkart IT Services",
        "agency_url": "https://codingkart.com",
        "country": "India",
        "city": "Indore",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "20-30",
        "decision_maker": "Abhinav Tiwari",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/iamabhinavtiwari",
        "contactability": "MEDIUM",
        "services": ["Shopify Plus Development", "WooCommerce Subscriptions", "Custom Apps", "Migrations", "CRO"],
        "certifications": ["Shopify Plus Partner"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "final_score": 72,
        "why_this_agency": "Shopify Plus Partner since 2013. 20-30 employees. 7-figure revenue brands served.",
        "comai_fit": "Shopify development for DTC brands. COMAI integrates with every store they build.",
        "pitch_angle": "Codingkart builds Shopify stores for DTC brands. COMAI adds WhatsApp commerce layer.",
        "source": "manual_research",
    },
    {
        "agency_name": "ControlF5",
        "agency_url": "https://controlf5.in",
        "country": "India",
        "city": "Indore",
        "agency_type": "Shopify Development Agency",
        "employees": "50-100",
        "contactability": "MEDIUM",
        "services": ["Shopify Development", "Custom Apps", "Mobile Apps", "UI/UX Design", "Digital Marketing"],
        "certifications": ["Shopify Partner"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 70,
        "final_score": 70,
        "why_this_agency": "Shopify Partner. 50-100 employees. Founded 2012. Global client base.",
        "comai_fit": "Full-service digital agency with Shopify expertise. COMAI adds WhatsApp commerce.",
        "pitch_angle": "ControlF5 builds Shopify stores for global brands. COMAI integrates as WhatsApp commerce layer.",
        "phone": "+91975552463",
        "email": "contact@controlf5.in",
        "source": "manual_research",
    },
    # === PERFORMANCE MARKETING AGENCIES ===
    {
        "agency_name": "Ministry of Marketing",
        "agency_url": "https://ministryofmarketing.in",
        "country": "India",
        "city": "New Delhi",
        "agency_type": "Performance Marketing Agency",
        "employees": "10-20",
        "decision_maker": "Madhav Monga",
        "decision_maker_role": "Founder",
        "contactability": "HIGH",
        "services": ["Performance Marketing", "Server-Side Data", "Omnichannel Attribution", "Meta Ads", "Google Ads", "AEO"],
        "tier": "A",
        "client_access_score": 80,
        "comai_fit_score": 75,
        "final_score": 77,
        "why_this_agency": "Pure-play performance media house. 20+ years experience. D2C, B2C, luxury brands. Server-side tracking expertise.",
        "comai_fit": "Enterprise D2C brands need WhatsApp commerce. Their attribution expertise pairs with COMAI's analytics.",
        "pitch_angle": "Ministry of Marketing runs performance for enterprise D2C brands. COMAI adds WhatsApp commerce to their growth stack.",
        "source": "manual_research",
    },
    {
        "agency_name": "Kreative & Co.",
        "agency_url": "https://kreativee.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "D2C Growth Agency",
        "employees": "50-100",
        "decision_maker": "Karan Goyal",
        "decision_maker_role": "Founder",
        "contactability": "MEDIUM",
        "services": ["Performance Marketing", "Creative Strategy", "Content", "Brand Building", "D2C Scaling", "Marketplace Growth"],
        "tier": "A",
        "client_access_score": 85,
        "comai_fit_score": 75,
        "final_score": 79,
        "why_this_agency": "250+ brands. $100M+ revenue generated for D2C brands in 2025. PayPal partnership. Daylight Capital backed.",
        "comai_fit": "Massive D2C portfolio. $100M+ revenue influenced. COMAI adds WhatsApp commerce to every client.",
        "pitch_angle": "Kreative & Co. generated $100M+ for 250+ D2C brands. COMAI adds WhatsApp commerce to their growth engine.",
        "source": "manual_research",
    },
    {
        "agency_name": "Digidarts",
        "agency_url": "https://digidarts.com",
        "country": "India",
        "city": "Gurugram",
        "agency_type": "Performance Marketing Agency",
        "employees": "50-100",
        "decision_maker": "Founding Team",
        "decision_maker_role": "Leadership",
        "contactability": "MEDIUM",
        "services": ["Performance Marketing", "Google Ads", "Meta Ads", "Amazon Ads", "SEO", "CRO", "D2C Scaling"],
        "tier": "A",
        "client_access_score": 80,
        "comai_fit_score": 75,
        "final_score": 77,
        "why_this_agency": "75+ ecommerce brands. 2500Cr+ gross revenue generated. 1000Cr+ spend managed. Pioneer 360° performance agency.",
        "comai_fit": "Massive ecommerce portfolio. COMAI adds WhatsApp commerce to their client base.",
        "pitch_angle": "Digidarts generated 2500Cr+ for 75+ brands. COMAI adds WhatsApp commerce layer to their entire portfolio.",
        "source": "manual_research",
    },
    {
        "agency_name": "Emveto",
        "agency_url": "https://emveto.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Performance Marketing Agency",
        "employees": "10",
        "decision_maker": "Dharmik Shah",
        "decision_maker_role": "Co-Founder & CEO",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Google Ads", "Amazon Ads", "Flipkart Ads", "Full-Funnel Growth", "Creative Strategy"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "final_score": 70,
        "why_this_agency": "Fast-growing. 30% MoM growth. Shark Tank-backed brands. 5-min response time. Lean team of 10.",
        "comai_fit": "Shark Tank brands need WhatsApp commerce. Quick turnaround agency.",
        "pitch_angle": "Emveto scales Shark Tank brands. COMAI adds WhatsApp commerce to their high-growth clients.",
        "source": "manual_research",
    },
    {
        "agency_name": "Nine Digitals",
        "agency_url": "https://ninedigitals.com",
        "country": "India",
        "city": "Ahmedabad",
        "agency_type": "Performance Marketing Agency",
        "employees": "10-20",
        "decision_maker": "Jigar Jaysinghani",
        "decision_maker_role": "Founder & CEO",
        "linkedin": "https://linkedin.com/in/jigar-jaysinghani",
        "contactability": "HIGH",
        "services": ["Google Ads", "Meta Ads", "Amazon Ads", "Bing Ads", "LinkedIn Ads", "CRO", "Shopify Development"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "final_score": 72,
        "why_this_agency": "8+ years. $500M+ revenue generated for brands. 60+ global accounts. 7.8x ROAS achieved.",
        "comai_fit": "eCommerce growth agency with Shopify expertise. COMAI integrates directly with their client stores.",
        "pitch_angle": "Nine Digitals generated $500M+ for 60+ brands. COMAI adds WhatsApp commerce to their growth engine.",
        "source": "manual_research",
    },
    {
        "agency_name": "Ecomaksh",
        "agency_url": "https://ecomaksh.com",
        "country": "India",
        "city": "Jaipur",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "5-10",
        "decision_maker": "Aksh Khandelwal",
        "decision_maker_role": "Founder & CEO",
        "linkedin": "https://linkedin.com/in/aksh-khandelwal-212486252",
        "email": "akshkhandelwal976@gmail.com",
        "contactability": "HIGH",
        "services": ["Performance Marketing", "Meta Ads", "Google Ads", "CRO", "Funnel Building", "Creative Testing"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "final_score": 72,
        "why_this_agency": "30+ D2C brands. 20Cr+ revenue generated. Fashion, electronics, jewellery, footwear focus.",
        "comai_fit": "D2C performance agency. Their clients need WhatsApp commerce for retention.",
        "pitch_angle": "Ecomaksh scales 30+ D2C brands. COMAI adds WhatsApp commerce for repeat purchases.",
        "source": "manual_research",
    },
    {
        "agency_name": "MixMedia Creatives",
        "agency_url": "https://mixmediacreatives.com",
        "country": "India",
        "city": "Pune",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "5-10",
        "decision_maker": "Deepak Agrawal",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/deepak-agrawal-84aa5319b",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Performance Creatives", "AI-Native Production", "Catalog Ads", "CRO", "Landing Pages"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "final_score": 72,
        "why_this_agency": "50Cr+ revenue influenced. 4-8x ROAS across skincare, haircare, supplements. AI-native creative systems.",
        "comai_fit": "D2C performance agency with AI focus. COMAI's AI chatbot complements their AI-native approach.",
        "pitch_angle": "MixMedia Creatives influences 50Cr+ revenue. COMAI adds AI-powered WhatsApp commerce.",
        "source": "manual_research",
    },
    {
        "agency_name": "Resultiq Digital",
        "agency_url": "https://resultiqdigital.com",
        "country": "India",
        "city": "Noida",
        "agency_type": "D2C Performance Marketing Agency",
        "employees": "5-10",
        "decision_maker": "Akash Saini",
        "decision_maker_role": "Founder & CEO",
        "linkedin": "https://linkedin.com/in/akash-saini-312496226",
        "email": "info@resultiqdigital.com",
        "contactability": "HIGH",
        "services": ["CRO", "Meta Ads", "Google Ads", "Shopify Development", "Email Marketing", "WhatsApp Marketing", "Social Media"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 80,
        "final_score": 72,
        "why_this_agency": "CRO-focused. Already does WhatsApp marketing. Shiprocket Preferred Partner. D2C clothing, kids, accessories.",
        "comai_fit": "Already does WhatsApp marketing manually. COMAI automates with AI chatbot + cart recovery.",
        "pitch_angle": "Resultiq Digital does WhatsApp marketing manually. COMAI automates with AI — better conversions, less effort.",
        "source": "manual_research",
    },
    {
        "agency_name": "MorphMedia",
        "agency_url": "https://morphmedia.in",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Performance Marketing Agency",
        "employees": "1-10",
        "decision_maker": "Chaitan Shah",
        "decision_maker_role": "Managing Partner",
        "linkedin": "https://linkedin.com/in/chaitanshah",
        "email": "sales@morphmedia.in",
        "contactability": "HIGH",
        "services": ["Performance Marketing", "SEO", "Website Development", "CRO", "Meta Ads", "Google Ads", "YouTube Ads"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "final_score": 70,
        "why_this_agency": "9+ years. 50Cr+ ad spend. 10x+ ROAS. Full-funnel: traffic + conversion + retention.",
        "comai_fit": "Full-funnel agency — traffic, conversion, retention. COMAI completes the retention layer.",
        "pitch_angle": "MorphMedia does full-funnel growth. COMAI adds WhatsApp commerce for retention and repeat purchases.",
        "source": "manual_research",
    },
    {
        "agency_name": "Digital Berries",
        "agency_url": "https://digitalberries.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Digital Marketing Agency",
        "employees": "10-20",
        "decision_maker": "Hussain Raniwala",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/hussainraniwala",
        "contactability": "MEDIUM",
        "services": ["Performance Marketing", "Brand Systems", "SEO", "Paid Media", "Social", "Influencers", "Web Design", "AI Automation"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 70,
        "final_score": 70,
        "why_this_agency": "100+ clients. India, UAE, UK presence. Full-service growth agency. AI automation focus.",
        "comai_fit": "Full-service agency with AI focus. COMAI fits naturally into their AI automation stack.",
        "pitch_angle": "Digital Berries does AI automation for 100+ clients. COMAI adds WhatsApp commerce AI.",
        "source": "manual_research",
    },
    {
        "agency_name": "Adonix",
        "agency_url": "https://adonix.in",
        "country": "India",
        "city": "Delhi",
        "agency_type": "D2C Growth Agency",
        "employees": "1-10",
        "decision_maker": "Deepanshu Gautam",
        "decision_maker_role": "Founder & CEO",
        "linkedin": "https://linkedin.com/in/deepanshu-gautam-680648262",
        "contactability": "HIGH",
        "services": ["Meta Ads", "Creative Strategy", "CRO", "Shopify Growth", "Performance Marketing"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "final_score": 70,
        "why_this_agency": "Fractional Head of Growth for D2C. 15Cr+ Meta ad spend managed. Shopify brand specialist.",
        "comai_fit": "Shopify D2C specialist. Their clients are perfect for WhatsApp commerce integration.",
        "pitch_angle": "Adonix scales Shopify D2C brands. COMAI adds WhatsApp commerce to their growth playbook.",
        "source": "manual_research",
    },
    {
        "agency_name": "Yashvi Konnect",
        "agency_url": "https://yashvikonnect.com",
        "country": "India",
        "city": "Ahmedabad",
        "agency_type": "eCommerce Growth Agency",
        "employees": "10-20",
        "decision_maker": "Krushang Shah",
        "decision_maker_role": "Founder & CEO",
        "contactability": "HIGH",
        "services": ["eCommerce SEO", "Performance Marketing", "CRO", "Shopify Development", "WooCommerce", "Website Speed Optimization"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 75,
        "final_score": 72,
        "why_this_agency": "IIM-A alumnus. 15+ years experience. 200+ international clients. 98% client retention rate.",
        "comai_fit": "eCommerce growth specialist with 200+ clients. COMAI integrates with every store.",
        "pitch_angle": "Yashvi Konnect serves 200+ eCommerce clients. COMAI adds WhatsApp commerce to their growth stack.",
        "source": "manual_research",
    },
    {
        "agency_name": "MetaSaurus",
        "agency_url": "https://metasaurus.in",
        "country": "India",
        "city": "Bengaluru",
        "agency_type": "D2C Enablement Agency",
        "employees": "1-10",
        "decision_maker": "Devanshu Raj",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/devanshuraj",
        "contactability": "HIGH",
        "services": ["Shopify Stores", "Performance Marketing", "Analytics", "Retention Marketing", "Logistics Management"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 80,
        "final_score": 72,
        "why_this_agency": "End-to-end D2C enablement. $150K+ ARR. 7x+ ROAS. IIM Rohtak graduate.",
        "comai_fit": "End-to-end D2C enablement — COMAI completes their retention/commerce stack.",
        "pitch_angle": "MetaSaurus provides end-to-end D2C enablement. COMAI adds WhatsApp commerce to their full stack.",
        "source": "manual_research",
    },
    {
        "agency_name": "Scribbld",
        "agency_url": "https://scribbld.in",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Creative and Marketing Agency",
        "employees": "50",
        "decision_maker": "Kajol Bheda",
        "decision_maker_role": "Founder & CEO",
        "contactability": "MEDIUM",
        "services": ["Brand Strategy", "Creative Campaigns", "Content Production", "Social Media", "Performance Marketing", "Influencer Marketing"],
        "tier": "B",
        "client_access_score": 75,
        "comai_fit_score": 65,
        "final_score": 69,
        "why_this_agency": "Forbes 30 Under 30. 50 employees. Nykaa, Amazon Prime, Haldiram's, Adani clients. Bootstrapped, profitable.",
        "comai_fit": "Creative agency with major D2C brand clients. COMAI adds WhatsApp commerce to their brand portfolio.",
        "pitch_angle": "Scribbld serves Nykaa, Amazon Prime, Haldiram's. COMAI adds WhatsApp commerce to their brand client portfolio.",
        "source": "manual_research",
    },
    {
        "agency_name": "BRBU Brands",
        "agency_url": "https://brbubrands.com",
        "country": "India",
        "city": "Pune",
        "agency_type": "eCommerce Brand Development Agency",
        "employees": "10-20",
        "decision_maker": "Aabha Naval",
        "decision_maker_role": "Co-Founder & CEO",
        "linkedin": "https://linkedin.com/in/aabha-naval-3504981b0",
        "contactability": "MEDIUM",
        "services": ["eCommerce Solutions", "Brand Strategy", "Visual Identity", "Cataloguing", "Content Creation", "Marketplace Management"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "final_score": 70,
        "why_this_agency": "D2C brand development. India, US presence. Design-led approach. 10-20 employees.",
        "comai_fit": "eCommerce brand development agency. Their clients need WhatsApp commerce from day one.",
        "pitch_angle": "BRBU Brands develops D2C brands. COMAI integrates WhatsApp commerce into their brand builds.",
        "source": "manual_research",
    },
    {
        "agency_name": "Huddle",
        "agency_url": "https://inahuddle.com",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Design-Led Growth Agency",
        "employees": "1-10",
        "decision_maker": "Ankit Anvekar",
        "decision_maker_role": "Co-Founder",
        "linkedin": "https://linkedin.com/in/ankitanvekar11",
        "contactability": "HIGH",
        "services": ["Design-Led Performance Marketing", "Meta Ads", "Google Ads", "Brand Strategy", "Creative Production"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 70,
        "final_score": 67,
        "why_this_agency": "Aditya Birla client. 23x ROAS. $122K in 6 weeks. Brand-first performance approach.",
        "comai_fit": "Brand-first performance agency. COMAI adds WhatsApp commerce to their brand clients.",
        "pitch_angle": "Huddle delivers brand-first performance. COMAI adds WhatsApp commerce to their client growth stack.",
        "source": "manual_research",
    },
    {
        "agency_name": "Digi Masala",
        "agency_url": "https://digimasala.com",
        "country": "India",
        "city": "Delhi",
        "agency_type": "Digital Marketing Agency",
        "employees": "5-10",
        "decision_maker": "Prachi Taank",
        "decision_maker_role": "Founder & CEO",
        "linkedin": "https://linkedin.com/in/prachi-taank-6918a7283",
        "contactability": "HIGH",
        "services": ["Amazon Growth", "Influencer Marketing", "Performance Marketing", "Social Media Marketing", "Brand Strategy", "Marketplace Consulting"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 70,
        "final_score": 70,
        "why_this_agency": "3000+ brand collaborations. 18 countries. Amazon seller specialist. D2C brand scaling.",
        "comai_fit": "Amazon sellers need WhatsApp commerce for D2C channel. COMAI adds WhatsApp to their marketplace strategy.",
        "pitch_angle": "Digi Masala works with 3000+ brands. COMAI adds WhatsApp commerce for their D2C brand clients.",
        "source": "manual_research",
    },
    {
        "agency_name": "Pure Billion Technologies",
        "agency_url": "https://purebillion.tech",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Shopify Development Agency",
        "employees": "10-20",
        "decision_maker": "Vineet Parekh",
        "decision_maker_role": "Co-Founder",
        "contactability": "MEDIUM",
        "services": ["Shopify Development", "Custom ERP", "AI Integration", "Headless Commerce", "Next.js Storefronts"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 75,
        "final_score": 70,
        "why_this_agency": "Shopify + ERP + AI integration. Small senior team. D2C brands across India, US, Europe, UAE.",
        "comai_fit": "Shopify + AI integration focus. COMAI's AI chatbot fits perfectly into their tech stack.",
        "pitch_angle": "Pure Billion builds Shopify + AI solutions. COMAI is the AI WhatsApp commerce layer for their clients.",
        "source": "manual_research",
    },
    {
        "agency_name": "Big Bang Commerce",
        "agency_url": "https://bigbangcommerce.io",
        "country": "India",
        "city": "Mumbai",
        "agency_type": "Shopify Development Agency",
        "employees": "5-10",
        "decision_maker": "Vishwajeet",
        "decision_maker_role": "Co-Founder",
        "contactability": "MEDIUM",
        "services": ["Shopify Development", "Store Design", "D2C Optimization", "WooCommerce Migration", "CRO"],
        "tier": "B",
        "client_access_score": 65,
        "comai_fit_score": 70,
        "final_score": 67,
        "why_this_agency": "Shopify agency for D2C brands. In-house team. Founder-led. Hundreds of stores built.",
        "comai_fit": "Shopify D2C specialist. COMAI integrates with every store they build.",
        "pitch_angle": "Big Bang Commerce builds Shopify stores for D2C. COMAI adds WhatsApp commerce layer.",
        "source": "manual_research",
    },
    {
        "agency_name": "Klixora",
        "agency_url": "https://klixora.com",
        "country": "India",
        "city": "Kurukshetra",
        "agency_type": "Performance Marketing Agency",
        "employees": "1-10",
        "decision_maker": "Anuraag Jayant",
        "decision_maker_role": "Founder",
        "contactability": "MEDIUM",
        "services": ["Meta Ads", "Google Ads", "Sales Funnels", "Landing Pages", "Shopify Setup & CRO", "Marketing Audits"],
        "tier": "C",
        "client_access_score": 55,
        "comai_fit_score": 75,
        "final_score": 65,
        "why_this_agency": "Shopify Partner. Performance-first. Lean studio model. D2C and digital service brands.",
        "comai_fit": "Shopify Partner + performance marketing. COMAI adds WhatsApp commerce to their client funnel.",
        "pitch_angle": "Klixora builds Shopify stores and runs performance marketing. COMAI adds WhatsApp commerce to close the loop.",
        "source": "manual_research",
    },
    {
        "agency_name": "GrowthMatrrix",
        "agency_url": "https://growthmatrrix.com",
        "country": "India",
        "city": "India",
        "agency_type": "eCommerce Growth Agency",
        "employees": "1-10",
        "decision_maker": "Rajarshi Chakraborty",
        "decision_maker_role": "Founder",
        "linkedin": "https://linkedin.com/in/entrepreneur-rajarshi",
        "contactability": "MEDIUM",
        "services": ["Google Ads", "Meta Ads", "CRO", "eCommerce Strategy", "Funnel Optimization", "Growth Strategy"],
        "tier": "C",
        "client_access_score": 60,
        "comai_fit_score": 70,
        "final_score": 65,
        "why_this_agency": "12 years experience. DTC & eCommerce focus. Systems-based growth approach.",
        "comai_fit": "eCommerce growth specialist. COMAI adds WhatsApp commerce to their growth systems.",
        "pitch_angle": "GrowthMatrrix builds scalable growth systems. COMAI adds WhatsApp commerce to their client stack.",
        "source": "manual_research",
    },
    {
        "agency_name": "Worldhook",
        "agency_url": "https://worldhook.com",
        "country": "India",
        "city": "India",
        "agency_type": "Shopify Plus Development Agency",
        "employees": "20-30",
        "contactability": "MEDIUM",
        "services": ["Shopify Plus Development", "Custom Store Development", "Checkout Optimization", "B2B Channel Setup", "Shopify Consulting"],
        "certifications": ["Shopify Plus Partner"],
        "tier": "B",
        "client_access_score": 70,
        "comai_fit_score": 70,
        "final_score": 70,
        "why_this_agency": "750+ projects. 11+ years. 60+ countries served. Shopify Plus development company.",
        "comai_fit": "Massive Shopify portfolio across 60+ countries. COMAI adds WhatsApp commerce to their builds.",
        "pitch_angle": "Worldhook built 750+ Shopify stores. COMAI adds WhatsApp commerce to their global portfolio.",
        "source": "manual_research",
    },
]

async def main():
    conn = await asyncpg.connect(host='127.0.0.1', port=5432, database='beacon', user='beacon', password='beacon_password')
    inserted = 0
    skipped = 0
    for lead in NEW_LEADS:
        lead['id'] = str(uuid.uuid4())
        lead['status'] = 'NEW'
        lead['outreach_sent'] = False
        lead['response_received'] = False
        lead['meeting_scheduled'] = False
        lead['partner_converted'] = False
        for key in ['notable_clients', 'notable_results', 'decision_makers', 'services', 'certifications', 'tags']:
            lead[key] = json.dumps(lead.get(key) or [])
        lead['evidence'] = json.dumps({})
        try:
            await conn.execute(
                '''INSERT INTO partner_leads (id, agency_name, agency_url, country, city, agency_type, employees, founded, clients, client_count, revenue_generated, revenue_managed, notable_clients, notable_results, decision_maker, decision_maker_role, decision_makers, email, phone, linkedin, contactability, services, certifications, tier, client_access_score, comai_fit_score, partner_intent, final_score, why_this_agency, comai_fit, pitch_angle, source, status, outreach_sent, response_received, meeting_scheduled, partner_converted, evidence, tags) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb,$15,$16,$17::jsonb,$18,$19,$20,$21,$22::jsonb,$23::jsonb,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38::jsonb,$39::jsonb)''',
                lead['id'], lead['agency_name'], lead.get('agency_url'), lead.get('country'),
                lead.get('city'), lead.get('agency_type'), lead.get('employees'), lead.get('founded'),
                lead.get('clients'), lead.get('client_count'), lead.get('revenue_generated'),
                lead.get('revenue_managed'), lead['notable_clients'], lead['notable_results'],
                lead.get('decision_maker'), lead.get('decision_maker_role'), lead['decision_makers'],
                lead.get('email'), lead.get('phone'), lead.get('linkedin'), lead.get('contactability'),
                lead['services'], lead['certifications'], lead.get('tier'),
                lead.get('client_access_score'), lead.get('comai_fit_score'),
                lead.get('partner_intent'), lead.get('final_score'),
                lead.get('why_this_agency'), lead.get('comai_fit'), lead.get('pitch_angle'),
                lead.get('source'), lead['status'], lead['outreach_sent'],
                lead['response_received'], lead['meeting_scheduled'],
                lead['partner_converted'], lead['evidence'], lead['tags']
            )
            inserted += 1
            print(f'  INSERTED: {lead["agency_name"]} (Tier {lead.get("tier", "C")} | Score {lead.get("final_score")})')
        except Exception as e:
            skipped += 1
            print(f'  ERROR: {lead["agency_name"]} - {e}')
    await conn.close()
    print(f'\n  Total inserted: {inserted}/{len(NEW_LEADS)} (skipped: {skipped})')

asyncio.run(main())
